flang-compiler/flang

- tools/flang1/flang1exe/exterf.c
- tools/flang1/flang1exe/interf.c
- tools/flang1/flang1exe/interf.h
- tools/flang2/docs/xflag.n
Improve module file consistency checks.
For now, this check is disabled using an ifdef macro (DO_MODULE_OPTION_CHECK).
The goal of the consistency check is to make sure we are not mixing modules
that are compiled with and without certain compiler flags like
-Mlarge_arrays.
The consistency checks do not yet work with libraries that are portable
across all compiler flag-sets. So, the checks are disabled for now.
> Pull 2017-08-08T16-48 Recent NVIDIA Changes

- CMakeLists.txt
cmake: allow dropping -Werror from c flags
gcc-7.1.0 generates a couple of warnings when compiling flang, so
allow to drop '-Werror' from the c flags. It is anyhow a bad idea
to enforce that flag as it is unclear what future compiler
versions will warn about.
Signed-off-by: Christoph Junghans <junghans@lanl.gov>
> cmake: allow dropping -Werror from c flags

- README.md
The documentation was incomplete for the case where the user is installing to a location that is not in the default path list.
> Install prefix docs fix

- tools/flang1/flang1exe/semsmp.c
- tools/flang2/docs/xflag.n
- tools/flang2/flang2exe/bih.h
- tools/flang2/flang2exe/bihutil.c
- tools/flang2/flang2exe/main.c
- tools/flang2/flang2exe/mwd.c
- tools/flang2/flang2exe/outliner.c
- tools/flang2/flang2exe/outliner.h
- tools/shared/pgifeat.h
- tools/shared/pragma.c
- tools/shared/pragma.h
Apply nodepchk to a loop/routine as a pragma nodepchk for simd
clause or simd construct. Since the host function has
information about nodepcheck, need to propagate the info to
outlined function when it was created because we lose sptr of
host function when we expand outlined function.
> Pull 2018-02-08T12-20 Recent NVIDIA Changes

- runtime/libpgmath/lib/common/cdexp.c
- runtime/libpgmath/lib/common/dispatch.c
- runtime/libpgmath/lib/common/log/gdlog2.c
- runtime/libpgmath/lib/common/log/gdlog4.c
- runtime/libpgmath/lib/common/log/gdlog8.c
- runtime/libpgmath/lib/common/misc.h
- runtime/libpgmath/lib/common/mthdecls.h
- runtime/libpgmath/lib/common/p_dpowi.c
- runtime/libpgmath/lib/common/pgstdinit.h
- runtime/libpgmath/lib/common/sincosf.c
- runtime/libpgmath/lib/ppc64le/builtin.c
- runtime/libpgmath/lib/x86_64/cpuid8664.h
- runtime/libpgmath/lib/x86_64/libm_inlines_amd.h
- runtime/libpgmath/lib/x86_64/mthdecls.h
libpgmath improvements.
Put back some of the target specific #ifdef pre-processor conditions in
libpgmath. This allows libpgmath to be built on multiple targets.
> Pull 2018-04-24T04-55 Recent NVIDIA Changes

- tools/flang1/flang1exe/main.c
Fix a bug exposed by Flang issue #492.
Enables flang1 to consume -es and -pp flags generated by the flang driver.
> Pull 2018-06-07T16-59 Recent NVIDIA Changes

- tools/flang2/flang2exe/cgmain.c
- tools/flang2/flang2exe/exp_rte.c
- tools/flang2/flang2exe/expsmp.c
- tools/flang2/flang2exe/expsmp.h
- tools/flang2/flang2exe/iliutil.c
- tools/flang2/flang2exe/kmpcutil.c
- tools/flang2/flang2exe/outliner.c
- tools/flang2/flang2exe/outliner.h
With new uplevel method, an uplevel structure is created on
the stack and pass to nested task routine.  This may not work
as the task may get executed after its task caller exit and
anything put on stack will be invalid.  Hence, copy address
of all shared variables on task data allocated by runtime.
The compiler also creates a pointer of DT_ANY. cgmain should
allow that dtype if it uses dt_nme to check for alignment.
> Pull 2018-07-27T12-49 Recent NVIDIA Changes

- runtime/flang/ieee_arithmetic.F95
This patch fixes a bug causing ieee17 test case to fail,
as described in bug report #263. It introduces correct values
for flags contrilling Rounding Mode selection on AArch64.
The valid values for Rounding Mode control field for AArch64 (bits
[23:22] of FPCR register) are listed here:
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0488d/CIHCACFF.html
> AArch64: fix for failing ieee17 test case: Introduce correct values for Rounding Mode selection

- tools/flang1/flang1exe/scan.c
The code initialised a pointer to a value that according to C is undefined
behavior (section 6.5.6, clause 8):
char *ip = id - 1; /* point 1 before id[] */
This variable is then conditionally incremented and written to in a
do-while loop, but if the condition was never true, the value '\0' is
written to address 'id - 1'.
The functionality of alpha() breaks when compiled with LLVM 7.
> Fix undefined behaviour in scan.c:alpha()

- include/flang/Error/errmsg-common.n
- runtime/flang/fioMacros.h
- runtime/flang/fortDt.h
- test/f90_correct/src/check.c
- tools/flang1/flang1exe/dtypeutl.c
- tools/flang1/flang1exe/semant2.c
- tools/flang1/flang1exe/semantio.c
- tools/flang1/flang1exe/semfunc.c
- tools/flang1/flang1exe/semutil.c
- tools/flang1/flang1exe/semutil2.c
- tools/flang1/utils/prstab/gram.tki
- tools/flang1/utils/prstab/gram.txt
- tools/flang2/flang2exe/cgmain.cpp
- tools/flang2/flang2exe/dtypeutl.cpp
- tools/flang2/flang2exe/exp_ftn.cpp
- tools/flang2/flang2exe/exp_rte.cpp
- tools/flang2/flang2exe/ili.h
- tools/flang2/flang2exe/iliutil.cpp
- tools/flang2/flang2exe/regutil.cpp
- tools/flang2/flang2exe/semutil0.cpp
- tools/flang2/flang2exe/upper.cpp
- tools/flang2/utils/ilitp/aarch64/ilitp.n
- tools/flang2/utils/ilitp/ilitp.cpp
- tools/flang2/utils/ilitp/ppc64le/ilitp.n
- tools/flang2/utils/ilitp/x86_64/ilitp.n
- tools/flang2/utils/ilmtp/aarch64/ilmtp.n
- tools/flang2/utils/ilmtp/ppc64le/ilmtp.n
- tools/flang2/utils/ilmtp/x86_64/ilmtp.n
- tools/flang2/utils/upper/upperilm.in
Front-end support for REAL(2)
This change contains the majority of infrastructure
to support real2 handling in the frontend.
There is not backend support for REAL(2) in Flang.
Adding ILMs and ILIs for real2 operations:
ILM: R2HF, HF2R, HFLD, HFST, HFCON, HFADD, HFMUL, HFSUB,
HFDIV, HFNEG, HFFUNC, HFCMP, HFAIF
ILI: HFADD, HFNEG, HFSUB, HFMUL, HFDIV, HFCMP, DFRHP,
HFCON, LDHP, HP2SP, SP2HP, STHP, ARGHP, CSEHP,
HFCMPZ, HFCJMP, HFCJMPZ
> Pull 2019-06-12T08-11 Recent NVIDIA Changes

- test/debug_info/lit.local.cfg
This patch adds minimal support for debug-info testing
infrastructure.
Post this debug-info related development should use this for
adding incremental test cases for regression and verification.
Discussion GitHub Issue:
https://github.com/flang-compiler/flang/issues/899
> [DebugInfo] Basic testing infra for debug-info testing

- test/f90_correct/inc/arithmetic_if.mk
- test/f90_correct/lit/arithmetic_if.sh
- test/f90_correct/src/arithmetic_if.f90
- tools/flang2/flang2exe/exp_ftn.cpp
- tools/flang2/flang2exe/ili.h
- tools/shared/atomic_common.h
When half precision reals were introduced the table (aif) used in the
ILI codegen for ArithmeticIF was increased in size and the offset for
INT*8 increased by one. But the entry for half precision was not
inserted, this causes an ICE for INT*8 type. The fix is to introduce
the entry for the half precision type before the INT*8 type.
Fix for https://github.com/flang-compiler/flang/issues/844
> Fix ICE in ArithmeticIF for INT*8 type

- test/debug_info/redundant-lexicalblock.f90
- tools/flang2/flang2exe/lldebug.cpp
Flang was creating a redundant lexical block at the beginning of of every subroutine debug info. This was causing debuggers to incorrectly assume the scope of a variable to be this lexical block.
This patch fixes this incorrect behavior by replacing all the debug info references of this redundant lexical block to the actual subroutine.
Brief explanation and correct behavior can be found here:
http://lists.llvm.org/pipermail/flang-dev/2020-April/000277.html
https://patchwork.ozlabs.org/patch/436971/
After this, GDB is correctly able to show formal arguments for the case of pass by value parameters.
> [DebugInfo]Fix for redundant lexical block in debug info

- test/tools/check_compilation.py
The script check_compilation.py is written for python 2.x and many tests fail when python 3.x is used. 
The print statements used in the script such as print title are not compatible with python 3.x 
The script is updated to support both python 2.x and pyton 3.x.
> Updating the test script to work with python 3.x

- test/f90_correct/inc/norm2.mk
- test/f90_correct/inc/norm2_double_precision.mk
- test/f90_correct/inc/norm2_error.mk
- test/f90_correct/inc/norm2_function.mk
- test/f90_correct/inc/norm2_single_precision.mk
- test/f90_correct/lit/norm2.sh
- test/f90_correct/lit/norm2_double_precision.sh
- test/f90_correct/lit/norm2_error.sh
- test/f90_correct/lit/norm2_function.sh
- test/f90_correct/lit/norm2_single_precision.sh
- test/f90_correct/src/norm2.F90
- test/f90_correct/src/norm2_double_precision.F90
- test/f90_correct/src/norm2_error.f90
- test/f90_correct/src/norm2_function.F90
- test/f90_correct/src/norm2_single_precision.F90
This patch adds unit tests for NORM2.
norm2.F90: Contains basic unit tests.
norm2_function.F90: Tests for return value as norm2 and for various kinds of arrays as argument.
norm2_single_precision.F90: Tests overflow with single-precision
norm2_double_precision.F90: Tests overflow with double-precision. Currently XFAILed due to #837
norm2_error.f90: Error tests for invalid input and arguments to norm2.
Signed-off-by: Caroline Concatto <caroline.concatto@arm.com>
> Unit tests for NORM2

- runtime/flang/const.c
- test/f90_correct/inc/maxloc14.mk
- test/f90_correct/inc/minloc14.mk
- test/f90_correct/lit/maxloc14.sh
- test/f90_correct/lit/minloc14.sh
- test/f90_correct/src/maxloc14.f90
- test/f90_correct/src/minloc14.f90
runtime/flang/const.c defines min_int{1,2,4,8} to be -max_int{1,2,4,8}, which is wrong for the two's complement representation. As a result, the MAXLOC runtime function will compare each element in the input array with an incorrect minimum value. If the array contains -huge(integer)-1, MAXLOC will return an unexpected result.
> [runtime] Fix off-by-one error in minimum integers

- test/debug_info/gdwarf_4.f90
- test/debug_info/gdwarf_5.f90
- tools/flang2/docs/xflag.n
- tools/flang2/flang2exe/ll_structure.cpp
Summary:
flang2 doesnt produce dwarf version 5 for -gdwarf-5.
Currently when -gdwarf-5 is passed to flang (driver), that doesnt
pass any corresponding (-x 120) option as it passes in case of
-gdwarf-2/3. flang2 binary picks -gdwarf-4 by default.
0x00000000: Compile Unit: length = 0x0000008e version = 0x0004
Now flang2 will identify gdwarf-4 and gdwarf-5 by -x 120 0x1000000
and -x 120 0x2000000, flang(driver) need to pass these option to flang
flang-driver changes will be pushed separately. After that -gdwarf-5
will work from glang driver.
Testing:
- check-llvm
- check-debuginfo
Change-Id: Ibb70438f0a024bb7a6425d8b022c9353d138fa98
> Support for -gdwarf-5 in flang2

- test/llvm_ir_correct/dot_preprocess.f90
- tools/flang1/flang1exe/accpp.c
The preprocessor in fortran detects 1.NE.PP_NUM as a number.
The fix uses the knowledge that a constant number can have
atmost one dot character in it. If more than one dot character
is seen then the scanning has gone too far ahead.
This fix removes PP_NUM from the number detected and allows
for substitution of PP_NUM with the defined preprocessor
value.
> Fix in preprocessing for Flexi app

- test/debug_info/enum.f90
- test/debug_info/parameter.f90
- tools/flang2/flang2exe/cgmain.cpp
- tools/flang2/flang2exe/llutil.cpp
- tools/flang2/flang2exe/llutil.h
- tools/flang2/flang2exe/upper.cpp
- tools/flang2/flang2exe/upper.h
This patch enables printing of routine scoped variables with parameter
attributes and enum values under debuggers.
- array and derived types with parameter attribute are fixed by
re-naming corresponding array constant values var$ac to var.
- scalar types with parameter attribute are fixed by generating
dbg.value intrinsics.
Example:
```
program main
integer (kind=8) :: svar
integer (kind=8) :: avar(5)
integer (kind=8), parameter :: spar = 99
integer (kind=8), parameter :: apar(5) = (/99, 98, 97, 96, 95/)
svar = spar
avar = apar
print *, svar, avar, spar, apar
end program main
```
For above test program, now gdb is able to show the value of variables
with parameter attribute.
```
. . . . .
(gdb) p spar
$1 = 99
(gdb) p apar
$2 = (99, 98, 97, 96, 95)
. . . . .
```
Note: #921 should be …
> flang gen-exec does not show routine variables with parameter attribute

- test/debug_info/conststring.f90
- tools/flang2/flang2exe/llutil.cpp
The current representation fails when character constant has '\0' in between.
Current representation terminates string there which is not correct.
It is fixed by representing character type with I8 type array.
Note: This issue was exposed after support of debug info for parameter
attribute. Below test case would work only after parameter attribute.
After #888 commit FUTURE-CHECK are changed to CHECK in test case.
test case
```
program main
character(10),parameter :: x = "abc"//achar(0)//"def"
print *,x
end
```
Current IR
```
call void @llvm.dbg.value (metadata [10 x i8] c"abc\00", metadata !17, metadata !18)
```
Fixed IR
```
call void @llvm.dbg.value (metadata [10 x i8] c"abc\00def   ", metadata !17, metadata !18)
```
> Correction of representation of string (character type) constants.

- test/f90_correct/inc/array_constructor.mk
- test/f90_correct/lit/array_constructor.sh
- test/f90_correct/src/array_constructor.f90
- tools/flang1/flang1exe/semutil2.c
Using a parameter array from a module which is constructed with implied-do
notation resulted in an ICE:
```
INTEGER*8, PARAMETER :: some_array(3) = (/ (i, i = 4241, 4243) /)
```
`const_eval()` computes the value of the index `i` in the implied do of the
array constructor. This function was returning a number literal, which was then
being fed into `mk_cval1()`.  This latter function expects a symbol table entry
when the number is a TY_INT8, and a number literal when it is a TY_INT.
This resulted in the number literal as it appeared in the source being
incorrectly treated as a symbol table index.
The fix is to use `mk_cval` which inserts the constant into the symbol table
and calls `mk_cval1` with what it expects.
This commit adds a test which sums an array which lives in another module and …
> Fix ICE interf:new_symbol_and_link, symbol not found

- docs/CMakeLists.txt
- docs/doxygen.cfg.in
- docs/index.rst
- tools/flang1/flang1exe/CMakeLists.txt
- tools/flang1/include/CMakeLists.txt
- tools/flang1/utils/n2rst/CMakeLists.txt
- tools/flang1/utils/prstab/CMakeLists.txt
- tools/flang2/flang2exe/CMakeLists.txt
- tools/flang2/utils/n2rst/CMakeLists.txt
* The `ast.n` file was moved to a different location causing cmake to fail to generate most of the existing documentation.
* Additionally, the unused rst files are now added to the list, so they are now also visible in the generated HTML.
* Sphinx build depends on generating all necessary rst files.
* Directories must be created before putting files into them.
* `gram.lis` file dependency added (thanks @bryanpkc!).
* renamed Cmake target `gen_sphinx_docs` to `flang2_gen_sphinx_docs` (to match existing `flang1_gen_sphinx_docs`)
@RichBarton-Arm , @kiranchandramohan , please review.
> Fix HTML docs generation

- test/f90_correct/lit/fc30.sh
- test/f90_correct/lit/ls07.sh
While testing flang-compiler/classic-flang-llvm-project#1, @gklimowicz found that two Flang tests were failing with LLVM 10 on OpenPower. We decided to exclude the tests until the test failures are properly investigated and fixed.
> f90_correct: exclude tests failing with LLVM 10 on OpenPOWER

- test/lit.cfg
- test/sema/aconst_with_null_subict.f90
- test/sema/lit.local.cfg
- tools/flang1/flang1exe/dinit.c
When initializing an ACONST (a constant array or derived type instance), flang1
assumes that the ACL (array constructor list) has a non-NULL subict, which
normally represents the contents of the array or object. But a derived type may
be defined to contain no component part, which causes flang1 to crash when
dereferencing the NULL subict, unnecessarily.
> [flang1] Do not assume unempty derived types

- test/debug_info/isopt-flag.f90
- tools/flang2/flang2exe/lldebug.cpp
flang is generating "isOptimized" flag as false in LLVM IR. Regardless of the whether it's an optimized build "-O2 -g or -O3 -g" or Un-optimized build "-g" or "-O0 -g".
**Incorrect behaviour** -
$flang -O3 -g -S -emit-llvm main.f90 -o- | awk /isOptimized/
$ isOptimized: false
flang -O0 -g -S -emit-llvm main.f90 -o- | awk /isOptimized/
$ isOptimized: false
**Corrected behavior** -
$flang -O3 -g -S -emit-llvm main.f90 -o- | awk /isOptimized/
$ isOptimized: true
$flang -O0 -g -S -emit-llvm main.f90 -o- | awk /isOptimized/
$ isOptimized: false
> [DebugInfo]: Corrected emission of isOptimized flag.

- test/debug_info/optimized-flag.f90
- tools/flang2/flang2exe/lldebug.cpp
For fortran programs -> flang is not emitting, DISPFlagOptimized.
**Incorrect behavior --**
$flang -O3 main.f90 -g -S -emit-llvm -o- | awk /DISPFlagOptimized/
!16 = distinct !DISubprogram(name: "main", scope: !2, file: !3, line: 5, type: !17, scopeLine: 5, spFlags: DISPFlagDefinition | DISPFlagMainSubprogram, unit: !2)
While clang does that for every function ->
$ clang -O3 main.c -g -S -emit-llvm -o- | awk /DISPFlagOptimized/
!7 = distinct !DISubprogram(name: "f", scope: !1, file: !1, line: 5, type: !8, scopeLine: 5, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition | **DISPFlagOptimized**, unit: !0, retainedNodes: !16)
**Corrected behavior --**
$flang -O3 main.f90 -g -S -emit-llvm -o- | awk /DISPFlagOptimized/
!16 = distinct !DISubprogram(name: "main", scope: !2, file: !3, line: 5, …
> [DebugInfo]: Fix for missing DISPFlagOptimized in debug metadata

- test/f90_correct/inc/use00.mk
- test/f90_correct/lit/use00.sh
- test/f90_correct/src/use00.f90
- tools/flang1/flang1exe/module.c
Fixes #890 .
`find_def_in_most_recent_scope()` sets the private bit to 0 when it found an alias. I assume that this is unintended behaviour, as the function is just supposed to find the symbol and not modify it. The private bit for an alias would be misleading, as explained in the comment a few lines later, so it gets cleared, but I don't think it should be cleared forever...
I suggest we save the original value of the flag and restore it at the end of the loop.
@kiranchandramohan , @RichBarton-Arm , please review. I am not sure I got the purpose of the `find_def_in_most_recent_scope()` right, but if I did we could consider doing the exact same thing for "hidden" flag, which gets overwritten in the next line.
> Fix private flag overwrite in find_def_in_most_recent_scope()

- include/flang/Error/errmsg-in.n
- test/directives/ivdep.f90
- test/directives/lit.local.cfg
- test/directives/novector.f90
- test/directives/omp_simd.f90
- test/directives/omp_simd_clause.f90
- test/directives/vector.f90
- test/directives/vector_directive1.f90
- test/directives/vector_directive2.f90
- test/directives/vector_directive3.f90
- tools/flang1/flang1exe/semsmp.c
- tools/flang2/docs/xflag.n
- tools/flang2/flang2exe/bih.h
- tools/flang2/flang2exe/bihutil.cpp
- tools/flang2/flang2exe/cgmain.cpp
- tools/flang2/flang2exe/iltutil.cpp
- tools/flang2/flang2exe/mwd.cpp
- tools/shared/pragma.c
This commit enables support for the following simd directives. These
directives can be used to control vectorisation performed by LLVM. It
works by passing vectorisation metadata to LLVM.
Note that these directives do not control any vectorisation performed
by flang itself.
1) !dir$ ivdep (ignore mem-dep and vectorise)
2) !$omp simd (requires -fopenmp, ignore mem-dep and vectorise)
3) !dir$ vector always (ignore cost and vectorise)
4) !dir$ novector
> Enable support for simd directives

- .github/workflows/build_flang.yml
This PR depends on https://github.com/flang-compiler/llvm/pull/87 and https://github.com/flang-compiler/flang-driver/pull/94.
On every commit to master and every PR created or modified github actions will:
* Download the pre-built llvm and flang-driver artifacts for installation and install them.
* Build and install OpenMP (about 30 seconds)
* Build libpgmath and flang project.
* Run make check-all to test the build.
The action takes about 7-8 minutes and gives a clear pass/fail result in the Pull Request, including links to the build logs.
Example PRs to demonstrate how this works:
* [Breaking the build](https://github.com/michalpasztamobica/flang/pull/1).
* [Breaking the tests](https://github.com/michalpasztamobica/flang/pull/3). 
* [Harmless change resulting in a successful …
> Enable github Actions for push to master and pull requests to master

- test/directives/lit.local.cfg
- test/directives/nounroll.f90
- test/directives/nounroll2.f90
- test/directives/unroll.f90
- test/directives/unroll_override.f90
- tools/flang2/docs/xflag.n
- tools/flang2/flang2exe/bih.h
- tools/flang2/flang2exe/bihutil.cpp
- tools/flang2/flang2exe/cgmain.cpp
- tools/flang2/flang2exe/iltutil.cpp
- tools/flang2/flang2exe/llutil.h
- tools/flang2/flang2exe/mwd.cpp
- tools/shared/pragma.c
This PR is based on #742 and cleans it up such that it no longer conflicts with #660 (which is included in this PR). A second commit is added to extend the directive to support user-specified unroll factors, and remove support for the old PGI-style syntax (which cannot be easily supported with `llvm.loop.unroll` metadata AFAICT). The new syntax is similar to what Intel Fortran supports:
```
!dir$ unroll
!dir$ unroll(6)
!dir$ unroll = 6
!dir$ nounroll
```
This PR also clarifies the usage of `XBIT(11)` and updates the test cases to make them more complete and understandable.
This PR needs to be rebased after #660 is accepted.
> Implement UNROLL(n) directive

- test/debug_info/result_var.f90
- tools/flang1/flang1exe/lowersym.c
- tools/flang2/flang2exe/lldebug.cpp
Debugger is not able to print function result variable.
---------------
(gdb) list
1       function func(i) result(j)
2           integer, intent(in) :: i ! input
3           integer             :: j ! output
4           j = i**2 + i**3
5        end function func
6
7        program xfunc
8           implicit none
9       integer :: i
10          integer :: func
(gdb) b 4
Breakpoint 2 at 0x201b1a: file funres.f90, line 4.
(gdb) r
Starting program: /dir/funres.fl
[Thread debugging using libthread_db enabled]
Using host libthread_db library
"/lib/x86_64-linux-gnu/libthread_db.so.1".
Breakpoint 1, func (i=3) at 2899_2.f90:4
4           j = i**2 + i**3
(gdb) p j
No symbol "j" in current context.
---------------
This is due to flang marking it as artificial variable. It is fixed now.
> Flang generated executable does not show result variable of function.

- test/debug_info/outervar.f90
- tools/flang2/flang2exe/lldebug.cpp
Currently outer variable are not being shown in debugger.
Please consider below program
````````````````````````````
1  program main
2    integer :: prog_i
3    prog_i = 99
4    call sub()
5  contains
6    subroutine sub()
7      print *,prog_i
8    end subroutine sub
9  end program main
Inside debugger...
(gdb) b 7
Breakpoint 2 at 0x400928: file outervar.f90, line 7.
(gdb) c
Continuing.
Breakpoint 2, main::sub () at outervar.f90:7
7          print *,prog_i
(gdb) p prog_i
$1 = <optimized out>
Now separate variable creation for contained subprogram is suppressed now.
> [DebugInfo] Internal subprogram variable is not accessible for printing in gdb

- tools/flang2/docs/xflag.n
The x flang command line option "-x 49" has missing entries.
This patch includes blanket entries for used sub-options as reserved, leaving others as AVAILABLE.
To get the used options simple script is used as 
```
> Updating X-flag entries for internal command line option "-x 49"

- test/f90_correct/inc/is_contiguous.mk
- test/f90_correct/lit/is_contiguous.sh
- test/f90_correct/src/is_contiguous.f90
- tools/flang1/flang1exe/semfunc.c
Fixes #936 .
As @mleair explained in [his comment](https://github.com/flang-compiler/flang/issues/936#issuecomment-720657812):
> I believe we missed the call to check_member() in the PD_is_contiguous case of ref_pd() in semfunc.c
This is correct. The reproducer now compiles fine and the other tests are still passing
I added `is_contiguous` test based on the issue's reproducer to prevent regression.
@mleair , @RichBarton-Arm , @kiranchandramohan , please review.
> Call check_member() for PD_is_contiguous

- test/llvm_ir_correct/omp_atomic_reduce_ice.f90
- tools/flang2/flang2exe/iliutil.cpp
Using non-standard types (logical or int with kind=1 and logical
with kind=8) in code with atomic instructions were leading to ICEs due
to a switch statement not handling these types. Adding these types to
the switch statement fixes the issue.
> Fix for ICE in atomic instruction generation

- test/directives/prefetch.f90
- tools/flang2/flang2exe/cgmain.cpp
- tools/flang2/flang2exe/exp_ftn.cpp
While Flang can parse a prefetch directive with the following syntax, it
currently ignores the directive:
!$mem prefetch <var1>[,<var2>[,...]]
This patch teaches flang2 to insert a call to @llvm.prefetch when it sees
the directive.
> [Flang2] Support Prefetch Directive

- runtime/flang/ftni64.h
- runtime/libpgmath/lib/x86_64/libm_inlines_amd.h
- tools/flang1/flang1exe/CMakeLists.txt
- tools/flang1/flang1exe/lower.h
- tools/flang1/flang1exe/lowerilm.c
- tools/flang1/flang1exe/optimize.h
- tools/flang1/utils/prstab/prstab.h
- tools/flang1/utils/prstab/prstab1.c
- tools/flang1/utils/symtab/CMakeLists.txt
- tools/flang1/utils/symtab/symini.cpp
- tools/flang2/flang2exe/CMakeLists.txt
- tools/flang2/utils/symtab/CMakeLists.txt
- tools/flang2/utils/symtab/symini.cpp
- tools/shared/utils/symacc.c
- tools/shared/utils/symutil.cpp
When trying to build flang using gcc-10 on top of `classic-flang-llvm-project` I came across some issues which were overlooked by gcc-9:
* an uninitialized array in one of `libpgmath`'s files (trivial to fix),
* a number of global symbols defined in header files (resulting in multiple definitions errors).
Regarding the second issue there is at least one case where the error is about a generated variable `STB stb` which lives in `symtabdf.h`, written by a utility program `fesymutil`. 
In the easier case it is quite straightforward to modify the code, so it doesn't give us multiple definition errors with `-fno-common` by just naming the structures and providing `extern` symbols in the header files and then moving their declarations to one of the c files. This approach is presented in …
> Fix gcc-10 compilaton issues

- .github/workflows/build_flang.yml
This PR mainly attempts to add more compilers and **switch CI to only use classic-flang-llvm-project for artifacts**.
Additionally it also adds minor improvements:
* Loop through artifact builds to find a successful one.
* Add html documentation build and upload it as an artifact.
Important note: This PR implements the proposal described in [this RFC](http://lists.llvm.org/pipermail/flang-dev/2020-November/000583.html). If there is any reason why we should stick to building `release_90` branch of [flang-compiler/llvm](https://github.com/flang-compiler/llvm) and [flang-compiler/flang-driver](https://github.com/flang-compiler/flang-driver), instead of switching to `release_100` branch of https://github.com/flang-compiler/classic-flang-llvm-project, please let me know.
If this PR is approved …
> Expand CI to run with GCC-9/10 and LLVM-9/10/11

- test/f90_correct/inc/rename00.mk
- test/f90_correct/lit/rename00.sh
- test/f90_correct/src/rename00.f90
- tools/flang1/flang1exe/module.c
- tools/flang1/flang1exe/semant.c
Fixes #889 .
In case the sptr is not in current scope - check if there is a symbol with same name available.
When an `alias` is being `rename`d, the newly created variable on the stack should also be of `ST_ALIAS` type.
I've also added a test based on @RichBarton-Arm 's reproducer.
@RichBarton-Arm , @kiranchandramohan , would you please review and help me set up the other reviewers appropriately?
> USE rename should check if renamed sptr is available in the scope

- test/debug_info/dwarfdump_prolog.f90
- test/debug_info/prolog.f90
- tools/flang2/flang2exe/cgmain.cpp
- tools/flang2/flang2exe/lldebug.cpp
- tools/flang2/flang2exe/lldebug.h
Due to this wrong debug_line section entry is created with wrong instruction
marked as 'prologue_end'. More details in committed test cases.
This causes debugger not skipping prologue when inserting break-point with
function/subroutine name.
To make breakpoint work as expected, some debugger (GDB) changes were
also required which are already committed as 
commit c2fd7faea8f2c3a267f276ceb6a95f9f537ea7c1
Author: Alok Kumar Sharma <AlokKumar.Sharma@amd.com>
Date:   Thu Aug 20 10:35:27 2020 +0530
> [DebugInfo] Flang should generate debug location for limited instructions in prolog

- .github/workflows/build_flang.yml
Github's default ubuntu image contents might have changed and we need to get the latest ubuntu database to install `sphinx`.
> Update apt data before installing sphinx

- test/openmp_examples/lit/runmake
- test/tools/check_compilation.py
Simplify the FileCheck pattern used in test/openmp_examples/lit/runmake; most of the original pattern was never generated and hence misleading. Prevent check_compilation.py from appending an extraneous space when printing a properly newline-terminated string.
I needed the FileCheck pattern change to catch test failures that would be erroneously reported as passing. The original problem has since been fixed (by 2beb1f781af26009535e511aa7e8ac063f86b65d), but I think these changes are still good to have, especially the check_compilation.py fix.
> [test] Minor FileCheck pattern fixes

- README.md
The readme still points to the old flang-dev list. The link times out for me now. Point it to the new flang-dev list page.
> Fix the readme to point to the correct flang-dev list

- tools/flang1/flang1exe/module.c
- tools/flang1/flang1exe/semfunc.c
- tools/flang1/flang1exe/semgnr.c
- tools/flang2/flang2exe/cgmain.cpp
This patch addresses the compilation and runtime issues of CP2K. Following additional flags are required for successful cp2k compilation and run.
1. -Hx,2,0x400000  - disable pointer optimizations
2. -Hx,47,0x1000000  - to disable calls to streamlined/dgemm-like matmul run-time routines
> Fixes to address cp2k compilation and runtime issues

- test/llvm_ir_correct/named_arguments.f90
- test/llvm_ir_correct/reshape_allocatable_order.f90
PR #966 has fixed two compile time problems which can be reproduced by the two minimal reproducers introduced by this commit.
> tests: two test cases supporting PR #966

- test/llvm_ir_correct/character_kind2.f90
- tools/flang1/flang1exe/transfrm.c
Fixes https://github.com/flang-compiler/flang/issues/864.
See issue description for details of the problem.
EDIT: In the course of the discussion and with great help from the reviewers it was proven that in fact `character(kind=2)` is using flang's extension `ncharacter` to handle multibyte characters. There are tests checking this basic functionality and we also managed to store an actual Kanji character correctly. So in the end the fix is not to raise internal compiler errors when `character(kind=2)` is used.
Original outdated description:
I tried to apply a minimum patch that will issue an error, as requested. It seems flang has been to some extent deliberately prepared to support `kind = 2`, because there is a dedicated type for it as well as some documentation. I left all the …
> Do not issue an error when character kind 2 is used

- .github/workflows/build_flang.yml
This PR depends on CI updates in classic-flag-llvm-project: https://github.com/flang-compiler/classic-flang-llvm-project/pull/12 and https://github.com/flang-compiler/classic-flang-llvm-project/pull/13, which update CI to build for both branches. They need to be merged first to produce correctly named artifacts for flang CI to use.
We now run all the builds for `release_100` (built with gcc-10, llvm-9,10,11) AND for `release_1xx` (gcc-10, llvm-9,10,11) AND for `release_90` + (just gcc-9 as per official instructions). All jobs run tests as well.
[Here](https://github.com/michalpasztamobica/flang/actions/runs/508599115)'s what a CI job will look like after merge (based on artifacts from a fork).
> Add the option to build release_11x branch of llvm with Github Actions

- tools/flang2/flang2exe/llassem.cpp
Since the presence of this bug cannot be reliably tested by usual
source code test cases, I've ensured that any malfunction of this algorithm
should result in a fatal ICE. Having this error detection check alone (without
fixing the bug itself) causes certain number of currently used test cases to
fail, this fact alone reveals how well this bug was hidden for years.
Fixes a problem signaled in #960.
> Fix hash collision handling routine that didn't work due to a fatal mistake (issue #960).

- .github/workflows/build_flang.yml
By default action is set up to:
1. Use 500MB size for cache
2. Compress the cache
3. Show the cache stats post-build to ensure it's used efficiently
> Add ccache support to GitHub Actions

- test/debug_info/allocatable_arr_param.f90
- test/debug_info/allocated.f90
- test/debug_info/allocated_nodup.f90
- test/debug_info/associated.f90
- test/debug_info/assumed_rank.f90
- test/debug_info/assumed_shape.f90
- test/debug_info/assumed_shape_non_contiguous.f90
- test/debug_info/assumed_shape_noopt.f90
- test/debug_info/assumed_size_array.f90
- test/debug_info/cray_ptr_param.f90
- test/debug_info/dertyp_striding.f90
- test/debug_info/module_allocatable_arr.f90
- test/debug_info/module_pointer_arr.f90
- test/debug_info/pointer_arr_param.f90
- test/debug_info/pointer_array_openmp.f90
- test/debug_info/ptr_arr_member.f90
- tools/flang1/flang1exe/lowersym.c
- tools/flang2/flang2exe/cgmain.cpp
- tools/flang2/flang2exe/cgmain.h
- tools/flang2/flang2exe/ll_structure.h
- tools/flang2/flang2exe/ll_write.cpp
- tools/flang2/flang2exe/lldebug.cpp
- tools/flang2/flang2exe/lldebug.h
- tools/flang2/flang2exe/upper.cpp
- tools/flang2/utils/symtab/symtab.n
This PR supports general array debugging (adjustable array, assumed shape array, assumed size array, allocatable and pointer array and assumed rank array).
It uses multiple upgrades to upstream LLVM which are backported to flang-LLVM as
LLVM11: https://github.com/flang-compiler/classic-flang-llvm-project/pull/14
LLVM10: https://github.com/flang-compiler/classic-flang-llvm-project/pull/8
LLVM9: https://github.com/flang-compiler/llvm/pull/86
Please note that this PR should be able to replace existing flang-LLVM DIFortranSubrage .
> [DebugInfo] Array debugging support with upgraded DISubrange

- .gitignore
- tools/flang2/flang2exe/CMakeLists.txt
- tools/flang2/flang2exe/asprintf.cpp
- tools/flang2/flang2exe/asprintf.h
- tools/flang2/flang2exe/kmpcutil.cpp
reasons why it's done this way:
1. I prefer to keep header files free of code.
2. windows functionality should not interfere with linux readability. windows should try to "also" work in addition to linux; therefore linux functions should be created on windows as a wrapper.
> add asprintf

- test/f90_correct/inc/array_constructor_nested_implied_do.mk
- test/f90_correct/lit/array_constructor_nested_implied_do.sh
- test/f90_correct/src/array_constructor_nested_implied_do.f90
- tools/flang1/flang1exe/dinit.c
- tools/flang1/flang1exe/semant.h
- tools/flang1/flang1exe/semutil2.c
- tools/flang1/utils/prstab/gram.txt
- tools/flang2/flang2exe/dinit.cpp
Fixes https://github.com/flang-compiler/flang/issues/871.
Summary of the changes in this PR:
* The array is resolved after the checks are performed - use a precalculated size and skip size checks performed before the array is ready.
* flang2 also needs to use a precalculated size.
* Add a test checking that the array is correctly initialised.
* Fixed inconsequent spacing in gram.txt and improved comments.
Rationale:
I believe that the root cause for the issue is that the algorithm performs some checks on an implied-do loop before it actually gets properly resolved. I failed to find an error in earlier stages of the implied-do handling and unless it is used to initialize an array the code works fine. I do not feel competent to redesign the whole algorithm of the data initialization, but I …
> Fix errors on array initialisation with an implied do loop

- test/f90_correct/inc/array_constructor_nested_implied_do.mk
- test/f90_correct/src/array_constructor_nested_implied_do.f90
- tools/flang1/flang1exe/dinit.c
- tools/flang1/flang1exe/dtypeutl.c
Fixes https://github.com/flang-compiler/flang/issues/992.
A new `cmpat_dtype_*` function is added that does a few preliminary checks to allow casting of arrays wherever this is possible.
Also a few test cases are added presenting the possibility of initializing arrays with different types.
> Nested implied do loop fix for real numbers

- test/ncar_kernels/CAM5_mg2_pgi/src/micro_mg_cam.F90
- test/ncar_kernels/PORT_binterp/src/kernel_binterp.F90
- test/ncar_kernels/PORT_reftra_sw/src/kernel_reftra_sw.F90
- test/ncar_kernels/PORT_sw_spcvmc/inc/t1.mk
- test/ncar_kernels/PORT_sw_spcvmc/src/rrtmg_sw_rad.F90
The NCAR test use selected_real_kind(12), therefore the  tolerance tests should also compare values until E-12.
This patch adds a tolerance  value TOL according to the architecture.
The consequence is to make the tests more robust
> Fixing NCAR test problems with error tolerance lower than E-12.

- .github/workflows/build_flang.yml
- CMakeLists.txt
- runtime/libpgmath/CMakeLists.txt
- runtime/libpgmath/test/CMakeLists.txt
- tools/flang1/flang1exe/CMakeLists.txt
- tools/flang2/flang2exe/CMakeLists.txt
This PR adds changes to allow Flang to be built on top of LLVM 12 (the candidate branch currently residing in https://github.com/Huawei-PTLab/classic-flang-llvm-project/tree/release_12x). NFCI.
LLVM 12's CMake modules have enabled more warnings and, as a result, building Flang with `-Werror` now fails. This PR turns off the `WITH_WERROR` option to work around the failures; a subsequent MR will fix the compiler warnings.
> LLVM 12 upgrade

- .github/workflows/build_flang.yml
As discussed in the Classic Flang weekly call - we want to move to supporting `release_12x` (already there thanks to @bryanpkc ) and drop support for `release_90`.
@bryanpkc , would you be able to remove the [build instructions](https://github.com/flang-compiler/flang/wiki/Building-Flang) for `release_90` or perhaps mark them as obsolete, please? I don't have access to modify the wiki page and it doesn't accept PRs :(
> Remove release_90 from Github Actions

- test/mp_correct/inc/taskloop_ice.mk
- test/mp_correct/lit/taskloop_ice.sh
- test/mp_correct/src/taskloop_ice.f90
- tools/flang1/flang1exe/vsub.c
Add missing case statement for end of Taskloop. Absence of this
case statement leads to some variables being marked as private
(instead of local). This prevents the allocation of these modules
on the stack and their further use in load or store statements.
This patch fixes https://github.com/flang-compiler/flang/issues/688.
> Fix for ICE in taskloop

- runtime/flang/ftni64.h
- runtime/flang/ftnncharsup.c
- runtime/flang/miscsup_com.c
There are places in the runtime code where AArch64 should be treated the same way as x86_64.
> runtime: ARM64 is a 64-bit architecture

- test/f90_correct/inc/mmul_misc3.mk
- test/f90_correct/lit/mmul_misc3.sh
- test/f90_correct/src/mmul_misc3.f90
- tools/flang1/flang1exe/func.c
Returning FALSE from mmul_arg() function prevents further preparations for making a call to the dgemm-alike f90_mmul_* flang runtime functions. Instead, it should fall back to making a call to one of the f90_matmul_* runtime functions.
> Fix for the issue #1005 : Do not call streamlined/dgemm-like matmul runtime routines for data layouts that could not be proven to be contiguous

- runtime/flangrti/CMakeLists.txt
- runtime/flangrti/llcrit.c
- test/mp_correct/inc/fork_omp.mk
- test/mp_correct/lit/fork_omp.sh
- test/mp_correct/src/fork.c
- test/mp_correct/src/fork_omp.F90
The llcrit.c code of flangrti runtime library creates internal locks
which are initialized on the first encounter of any Fortran procedure
that contains at least one OpenMP directive. The flang compiler emits
a call to one of the two functions modified by this patch at the
beginning of every Fortran procedure containing at least one OpenMP
directive. When executed for the first time, these functions
initialize internal locks and modify corresponding static global
variable confirming the initialization has actually occured. On any
subsequent execution, these functions make use of those locks.
Unfortunately, the values of those global indicator variables are not
being reset at fork, hence the locks are not being initialized in the
child processes. Any attempt of using those internal locks …
> runtime: register atfork handler to re-initialize internal flangrti locks at fork

- .github/workflows/build_flang.yml
Previously the native compiler was used, but this resulted in some tests failing for X86 and AArch64.
> Github Action use the prebuilt clang to build flang

- test/f90_correct/inc/string_array_pointer_1.mk
- test/f90_correct/inc/string_array_pointer_2.mk
- test/f90_correct/inc/string_array_pointer_3.mk
- test/f90_correct/inc/string_array_pointer_4.mk
- test/f90_correct/inc/string_array_pointer_5.mk
- test/f90_correct/lit/string_array_pointer_1.sh
- test/f90_correct/lit/string_array_pointer_2.sh
- test/f90_correct/lit/string_array_pointer_3.sh
- test/f90_correct/lit/string_array_pointer_4.sh
- test/f90_correct/lit/string_array_pointer_5.sh
- test/f90_correct/src/string_array_pointer_1.f90
- test/f90_correct/src/string_array_pointer_2.f90
- test/f90_correct/src/string_array_pointer_3.f90
- test/f90_correct/src/string_array_pointer_4.f90
- test/f90_correct/src/string_array_pointer_5.f90
- tools/flang1/flang1exe/dpm_out.c
This patch fixes a bug in pointer association that would set the type length of a `CHARACTER(:), POINTER` variable to an incorrect value, which would lead to a crash in the runtime during I/O.
This is a first attempt to fix issue #1008. We are not certain whether `emit_alnd_secd` is the best spot to fix this problem, nor how many other scenarios (apart from the rank-1 simply contiguous target case we have analyzed) we are not handling correctly. Advice from the community would be most welcome.
Based on a patch originally by Peixin Qiao.
> [flang1] Set type length of string array pointer

- test/llvm_ir_correct/critical_entries.f90
- tools/flang2/flang2exe/expsmp.cpp
This patch adds missing check for multiple entries in a function
that builds prologue for a Fortran function (or subroutine) that
contains at least one OpenMP directive.
Since ll_save_gtid_val() function usually used for single-entry
Fortran functions can handle only one entry, processing of multiple
entries is handled similarly in a for loop.
A short test case which validates this patch is also added
to the commit.
> Fix for segfault in multiple entries OpenMP functions (fixes #638 )

- test/f90_correct/inc/io28.mk
- test/f90_correct/lit/io28.sh
- test/f90_correct/src/io28.f90
- tools/flang1/flang1exe/semantio.c
The test case is as following :
```fortran
program test
type my_type
integer :: i
integer :: j
integer :: k
end type my_type
character(80) :: str1, str2
type(my_type), dimension(3) :: t
t(1) = my_type(11, 12, 13)
t(2) = my_type(21, 22, 33)
t(3) = my_type(31, 32, 33)
print *, t(func())
contains
integer function func()
integer, save :: i = 1
func = i
i = i + 1
end function
end
```
The correct result should be:
`         11          12          13`
But flang print incorrect result:
`         11          22          33`
Flang calls incorrectly `func()` three times and prints the values of `t(1)%i`, `t(2)%j` and `t(3)%k`.
> Fix error of outputting derived type.

- .github/workflows/build_flang.yml
- .github/workflows/build_flang_arm64.yml
As discussed in the Wednesday call and as a follow-up of https://github.com/flang-compiler/classic-flang-llvm-project/pull/39 and  https://github.com/flang-compiler/classic-flang-llvm-project/pull/41 we want to use the docker image created and pushed to ghcr.io in `classic-flang-llvm-project` to safely build and test PRs on Aarch64 machines provided by Arm.
Docker and Github Actions scripts are running on a non-root user account and within the docker instance we also provide unprivileged accounts, to ensure as much safety as possible (Github explicitly warns against someone trying to build malicious code in a PR to public repos).
Two servers are provided, which should easily suffice for the needs of Flang project. One build&test takes about 3 minutes.
> Add ARM64 CI

- test/debug_info/redundant_inst.f90
- tools/flang2/flang2exe/cgmain.cpp
flang was performing some opts even at "-g -O0" level.
Speifically, CSE is getting performed uncoditionally just before
the translation of the `store` instructions from ILI to LLVMIR.
Resulting in loss of debug-info and failures in GDB/gdb.fortran
testsuite. This patch inserts a check to disable the CSE opt if
it is not enabled.
Note: In flang CSE is enabled at `>=O1` optimization level.
> [DebugInfo] line table entry missing for statements

- runtime/libpgmath/lib/common/CMakeLists.txt
This patch fixes link-time issues described in bug report #1056 on
x86_64 machines. The commit in PR #695 has removed duplicated files,
kidnnt.c among them. Unfortunately, due to a sudden omission, the
original kidnnt.c file was not listed for being built for x86_64
targets.
> Fix x86_64 linker issues caused by PR #695

- runtime/flang/alias.c
These aliased OpenMP function defined as void,
and these void functions should not return a value.
The error is reported by clang-cl 12.0.0.
> Fix the build on Windows

- tools/shared/utils/machar.cpp
To avoid dereferencing string end iterator, extend tokenize_line loop with an extra condition
to detect the end of the string.
Since it causes out of range assertion error on Windows (xstring).
> machar: fix assertion failure on Windows

- .github/workflows/build_flang.yml
- .github/workflows/build_flang_arm64.yml
- build-flang.sh
As discussed in the Wednesday call - build scripts will make it easier to reproduce CI runs for users.
They were tailored with current CI setup in mind and the CI scripts were adjusted to use them.
I was partially inspired by @bryanpkc 's scripts available [here](https://github.com/Huawei-PTLab/classic-flang-llvm-project/wiki). Thanks, Bryan!
A PR to `classic-flang-llvm-project` will follow with similar build scripts introduced there.
> Add build scripts and switch CI to use them

- test/directives/vector_directive1.f90
- test/directives/vector_directive3.f90
- tools/flang2/docs/xflag.n
- tools/flang2/flang2exe/cgmain.cpp
- tools/flang2/flang2exe/llutil.h
- tools/shared/pragma.c
This PR adds loop directive support for !dir$ vector always (XBIT/XFLAG: 191/0x2).
It uses the llvm.loop.parallel_accesses metadata with the companion - llvm.access.group metadata.
(Created new PR as I had deleted the fork of the older one due to my misunderstanding).
@kiranchandramohan please add the reviewers here.
> [Flang2] Support for vector always loop directive

- test/f90_correct/inc/rename01.mk
- test/f90_correct/lit/rename01.sh
- test/f90_correct/src/rename01.f90
- tools/flang1/flang1exe/module.c
Fixes https://github.com/flang-compiler/flang/issues/1014 (linker error).
Test added, based on @pawosm-arm 's reproducer, to cover the problematic scenario.
The comment in the code suggests that the symbol should be hidden, but instead it sets it to be private.
Actually, even after removing the whole "hiding" `if` clause from line 729-740 I got all tests to pass just fine and I fail to see the purpose of this code snippet at all.
However, following the golden rule of working with legacy code I propose to make the smallest possible change that fixes our issue and leave the rest of the code intact.
> Hide original alias for a renamed subprogram instead of making it private

- test/llvm_ir_correct/sincos.f90
- tools/flang2/flang2exe/cgllvm.h
- tools/flang2/flang2exe/cgmain.cpp
- tools/flang2/flang2exe/cgmain.h
It turned out we are losing crucial optimization opportunities by not marking callsites for runtime library math functions with 'nounwind', 'readnone' and 'willreturn' attributes of LLVM-IR. These two patches are fixing that.
> Make use of 'nounwind', 'readnone', 'willreturn' LLVM-IR attributes

- test/f90_correct/src/wa04.f90
- tools/flang2/flang2exe/dinit.cpp
The original fallthrough behaviour was probably not intentional.
This patch was part of #1066 but since it is no longer obviously NFCI, we have put the change in a separate patch.
> [flang2] Fix fallthrough in `mk_cmp` (dinit.cpp)

- tools/flang1/flang1exe/dinit.c
This patch fixes an obviously malformed `switch` statement, which evaluates
intrinsic calls with constant arguments in data initializers. After the
fix, the default case (which was never exercised) would cause spurious
warnings, so the warning is turned into an ICE in the applicable case.
> [flang1] Fix malformed `switch` statement in dinit.c

- tools/flang2/flang2exe/mwd.cpp
`tools/flang2/flang2exe/mwd.cpp` is causing Clang 12 to complain about unused functions. The file contains mostly undocumented `static` functions that are apparently used for debugging (a comment at the top of the file calls them "mw's dump routines").
This patch simply deletes the functions that were causing Clang 12 to complain. Even though most of the routines are guarded with `#if DEBUG`, their `static`-ness and lack of use will still cause problems in a debug build. In #1071, similar debug functions in other files are declared non-`static` to avoid the warnings; we could do the same for the ones in `mwd.cpp`, depending on how useful the community thinks these routines are. If they aren't being used by anyone, perhaps deleting them isn't a problem.
> [flang2] Remove unused functions from mwd.cpp; NFC

- tools/flang1/flang1exe/semutil2.c
Place parentheses around assignments in conditions to silence `-Wparentheses` warnings.
In my code review so far, there seems to be only one such case. However, some of the roll-up fixes in subsequent PRs might fix this warning as well. I will move those fixes into this PR as I come across them.
> [flang1] Fix `-Wparentheses` warnings; NFC

- tools/flang1/flang1exe/accpp.c
In `tools/flang1/flang1exe/accpp.c`, the function `delete` writes a terminating `NULL` to its `char *` argument when the argument is longer than `MAXIDLEN`, only for passing it to `strcmp`. Using `strncmp` instead allows the parameter to be declared `const char *`, which silences compiler warnings and also eliminates an unnecessary surprising behaviour.
> [accpp] Prevent `delete()` from writing to its argument

- tools/flang2/flang2exe/dinit.cpp
An `assert` call in `tools/flang2/flang2exe/dinit.cpp` seems to be ineffectual, and is causing compile-time `-Wsign-compare` warnings. This patch simply deletes it.
> [flang2] Delete dead code causing compile-time warnings; NFCI

- runtime/flang/nmlread.c
- runtime/flang/open.c
- runtime/flang/pack.c
Functions with 32-bit `CLEN` parameters, e.g. `OPEN` and `UNPACKC`, should delegate to the respective versions with 64-bit `CLEN` parameters, i.e. `OPENA` and `UNPACKCA`, instead of themselves, resulting in infinite recursion.
Also fix a typo in the declaration of `LDR_INTERN_INITA`, ensuring that the uppercase and lowercase versions of the symbol are consistent.
> [runtime] Fix OPEN and UNPACKC call delegation

- runtime/flang/miscsup_com.c
`PRESENTC` calls `PRESENTCA` but forgets to return the latter's return value.
> [runtime] Fix PRESENTC delegation

- runtime/flang/red_norm2.c
Runtime functions written in Fortran are called from C code in red_norm2.c, without declaration. Adding the declarations fixes a number of `-Wimplicit-function-declaration` warnings.
> [runtime] Declare NORM2 functions in red_norm2.c; NFCI

- runtime/flang/f90alloc.h
This function is called outside allo.c by `DEALLOC_POLY03A` in type.c, and so must be declared in the header to avoid a compiler warning.
> [runtime] Declare DEALLOC03A in f90alloc.h; NFCI

- test/f90_correct/inc/apower.mk
- test/f90_correct/lit/apower.sh
- test/f90_correct/src/apower.f90
- tools/flang1/flang1exe/ast.c
The test case is following:
```fortran
program test
integer :: i1, i2, res(2)
i1 = -1
i2 = -8
res(1) = i1 ** i2
res(2) = i1 ** (-7)
print *, res
end
```
the result with `-O0` and `-O1` is correct:
`           1            -1`
the result with `-O2`, `-O3`, and `-Os` is incorrect:
`           0            0`
> Fix power operation optimization when the left operand is -1 and the right is a negative integer.

- test/debug_info/debug_module_import.f90
- test/debug_info/nametable.f90
- tools/flang2/docs/xflag.n
- tools/flang2/flang2exe/ll_write.cpp
- tools/flang2/flang2exe/lldebug.cpp
This option is used to generate extra debug information.
i.e
DWARFv4
`flang -gdwarf-4 -gpubnames test.c` will generate `.debug_pubnames` and
`.debug_pubtypes` in the executable.
DWARFv5
`flang -gdwarf-5 -gpubnames test.c` will generate `.debug_names` in
the executable.
Prior to this change these sections were getting generated by default.
These sections were extra and may or maynot be used by the debugger. Hence
generation of these sections are bind to this `-gpubnames` option.
This behavior is analogous to `clang`, `gcc`, gfortran.
> [DebugInfo] Support for `-gpubnames` option in `flang`

- runtime/flang/matmul.h
Runtime functions written in Fortran are called from C code. Declaring them properly silences a number of `-Wimplicit-function-declaration` warnings.
Also clang-format the file.
> [runtime] Declare MATMUL functions in matmul.h; NFCI

- test/f90_correct/inc/string_array_pointer_6.mk
- test/f90_correct/inc/string_array_pointer_7.mk
- test/f90_correct/lit/string_array_pointer_6.sh
- test/f90_correct/lit/string_array_pointer_7.sh
- test/f90_correct/src/string_array_pointer_6.f90
- test/f90_correct/src/string_array_pointer_7.f90
- tools/flang1/flang1exe/dpm_out.c
- tools/flang1/flang1exe/outconv.c
The test case is generated from the issue #1059.
```
program testsize
implicit none
type t1
character(:), pointer :: ptr(:)
end type t1
type(t1) :: var
character(:), pointer :: ptr2(:)
allocate(var%ptr(1), source="hello world")
allocate(ptr2(3), source="hello")
print *, var%ptr
print *, var%ptr(1)
print *, ptr2(3)
end program testsize
```
The breakpoint is set at function `convert_template_instance` in outconv.c, and the type descriptor set statements for `allocate(var%ptr(1), source="hello world")` are dumped as follows:
```
(gdb) b convert_template_instance
...
(gdb) p dsstds(0,0)
subprogram 1 testsize:
std:1    ast:66    lineno:9           var%ptr$sd(11_8) = 1_8
std:2    ast:67    lineno:9           var%ptr$sd(12_8) = 1_8
std:4    ast:79    lineno:9           var%ptr$sd(4_8) = 11_8 …
```
> [flang1] Set type length for a derived type member

- lib/ArgParser/arg_parser.c
- lib/ArgParser/debug_action.c
- tools/flang1/utils/ast/astutil.c
- tools/flang2/flang2exe/cgmain.cpp
- tools/flang2/flang2exe/kmpcutil.cpp
- tools/flang2/flang2exe/ll_structure.cpp
- tools/flang2/flang2exe/llutil.cpp
- tools/shared/utils/symutil.cpp
This patch adds diagnostic pragmas to parts of the code where fixing compile-time warnings is non-trivial:
1. `-Wcast-qual` warnings for type casts to/from `hash_key_t` and `hash_value_t` due to the const-ness in those typedefs. 
2. `-Wmissing-field-initializers` warnings for structure definitions generated with tools such as `astutil` and `fsymutil`.
Re-designing the hash table API and fixing the code generators is beyond the scope of fixing #1065 and left as future work.
> [flang1][flang2] Work around warnings with diagnostic pragmas; NFCI

- test/f90_correct/inc/common_01.mk
- test/f90_correct/lit/common_01.sh
- test/f90_correct/src/common_01.f90
- tools/flang1/flang1exe/optutil.c
- tools/flang2/flang2exe/dtypeutl.cpp
- tools/flang2/flang2exe/dtypeutl.h
- tools/shared/nmeutil.c
Fix the bug while using common in module and subroutine, the testcase is following:
```fortran
module mod1
integer :: mi1
common /com1/ mi1
contains
subroutine newmi1()
mi1 = 30
end subroutine newmi1
end module mod1
subroutine sub(x)
use mod1
integer :: si1, x
common /com1/ si1
si1 = 40
mi1 = 50
if(si1 == mi1)  x = 1
end subroutine sub  
program p
use mod1
integer :: res(5)
integer :: pi1
common /com1/ pi1
res = 0
pi1 = 10
mi1 = 20
if(pi1 == mi1)    res(1) = 1
if(pi1 == 20)     res(2) = 1
call newmi1()
mi1 = 20
pi1 = 10
if(pi1 == mi1)    res(3) = 1
if(mi1 == 10)     res(4) = 1
call sub(res(5))
do i = 1,5
if (res(i) == 1) print *, "case ", i, "passed."
if (res(i) == 0) print *, "case ", i, "failed."
end do
end program p                               
```
the result while -O0 is correct: …
> Do not optimize common block variable that is potentially aliased

- .gitignore
Often it is necessary to manage more build diretories in parallel which
are not handled in gitignore file. So this PR aims to extend the build pattern
with an 'asterisk' to match any build diretories which starts with build.
> Ignore all build directories which starts with 'build'

- lib/scutil/host-fp-folding.c
- lib/scutil/legacy-folding-api.c
- Do not use `STDC FENV_ACCESS` pragma on AArch64 which is not supported by GCC and Clang.
- Use unsigned wrap function for `DBLUINT64`.
> [scutil] Fix a couple of minor compilation warnings; NFCI

- runtime/flang/backspace.c
- runtime/flang/close.c
- runtime/flang/error.c
- runtime/flang/fmtwrite.c
- runtime/flang/ldwrite.c
- runtime/flang/nmlwrite.c
- runtime/flang/rewind.c
Use the existing io functions such as __io_binary_mode and
__io_setmode_binary.
> win: Fix io function names

- test/debug_info/producer.f90
- tools/flang2/flang2exe/lldebug.cpp
- tools/flang2/flang2exe/main.cpp
- tools/shared/utils/global.h
Currently Flang contains only compiler information for DWARF attribute DW_AT_producer.
``````````````
_llvm-dwarfdump test.o | grep DW_AT_producer_
DW_AT_producer    (**" F90 Flang - 1.5 2017-05-01"**)
Other compilers include compiler options as well.
_llvm-dwarfdump test.gf.o | grep DW_AT_producer_
DW_AT_producer    (**"GNU Fortran2008 7.5.0 -mtune=generic -march=x86-64 -gdwarf-5 -fintrinsic-modules-path /usr/lib/gcc/x86_64-linux-gnu/7/finclude"**)
``````````````
Current Patch includes compiler options also for Flang
This is done by adding a field "flags", rest is taken care by LLVM back-end.
!2 = distinct !DICompileUnit(language: DW_LANG_Fortran90, file: !3, producer: " F90 Flang - 1.5 2017-05-01", isOptimized: false, **flags: "'+flang -gdwarf-5 producer.f90 -S -emit-llvm'"**, …
> [DebugInfo] Flang should include compiler options in DW_AT_producer

- test/f90_correct/inc/pure_function.mk
- test/f90_correct/lit/pure_function.sh
- test/f90_correct/src/pure_function.f90
- tools/flang1/flang1exe/semutil.c
Adding ST_MODPROC to switch() options in mkvarref() to fix an issue
relating Pure Function not being properly detected.
The issue occours because the pure function type has assignated
ST_MODPROC and is not recognized.
In the case of the Workaround, the type is ST_PROC. Debug reveald
that the assignated types are correct, but the probem is that
ST_MODPROC has no action defined, hence an error in the compiler.
The soluton is to add ST_MODPROC into the same section as ST_PROC
in order to perfom the same actions
Fixes #1016
> Fix adding ST_MODPROC case in function mkvarref()

- runtime/include/memops.h
ssize_t is not available type on Windows, so
it needs to use SSIZE_T from Windows Data Types.
> win: Define ssize_t on Windows

- test/llvm_ir_correct/iso_fortran_env_functions.f90
- tools/flang1/flang1exe/exterf.c
The following test case is generated from the workload CP2K and reported by issue #896.
```
module usermod
use iso_fortran_env
end module usermod
program cp2k
use usermod
use iso_fortran_env, only: compiler_version, compiler_options
implicit none
character(len=:), allocatable :: version_var
character(len=:), allocatable :: options_var
version_var = compiler_version()
options_var = compiler_options()
print *, version_var
print *, options_var
end program cp2k
```
The functions `compier_version` and `compier_options` are exported in `iso_c_binding` library, which is shown in `usermod.mod` when compiling the code. The stype of the two functions is set to `ST_INTRIN` when they are imported by entering the if branch of `iso_c_binding`, which leads to the error.
```
$ flang test.f90
(error …
```
> [Flang1] Fix bug in exporting iso_fortran_env (encountered in CP2K #896)

- test/f90_correct/inc/en03.mk
- test/f90_correct/inc/en04.mk
- test/f90_correct/lit/en03.sh
- test/f90_correct/lit/en04.sh
- test/f90_correct/src/en03.f90
- test/f90_correct/src/en04.f90
- tools/flang1/flang1exe/lowersym.c
- tools/flang1/flang1exe/semfin.c
- tools/flang2/flang2exe/cgmain.cpp
- tools/flang2/flang2exe/ll_ftn.cpp
Fix error of processing entry statement:
* Compiling error when return type of entry is complex/pointer/array.
* Inconsistent with Fortran 2008 standard, ISO/IEC JTC 1/SC 22/WG 5/N1830
section-12.6.2.6 (If the characteristics of the result of the function
named in the ENTRY statement are the same as the characteristics of the
result of the function named in the FUNCTION statement, their result
variables identify the same variable, although their names need not be
the same).
> Fix error of processing entry statement.

- test/debug_info/dertyp_member_ptr.f90
- tools/flang2/flang2exe/lldebug.cpp
Compiler generated artificial variables were being leaked, which
is fixed now.
Please consider below testcase and its debug session.
````````````
program main
implicit none
type dtype
real, pointer :: sclrptr
end type dtype
real, target :: rval = 0.5
type(dtype) :: dvar
dvar%sclrptr => rval
end program main
````````````
Inside debugger
````````````
(gdb) pt dvar
type = Type dtype
real :: sclrptr
PTR TO -> ( real :: sclrptr$p )
End Type dtype
(gdb) p dvar
$1 = ( sclrptr = 2.96079792e-39, sclrptr$p = 0x203d80 <.STATICS1> )
`````````````
After fix
`````````````
(gdb) pt dvar
type = Type dtype
PTR TO -> ( real :: sclrptr )
End Type dtype
(gdb) p dvar
$1 = ( sclrptr = 0x203d60 <.STATICS1> )
(gdb) x/f 0x203d60
0x203d60 <.STATICS1>:   0.5
> [DebugInfo] Fix debug info for derived type having scalar pointer member

- test/llvm_ir_correct/omp_atomic_load_logical.f90
- tools/flang2/flang2exe/iliutil.cpp
This issue was haunting our OpenMP ATOMIC examples involving LOGICAL types. Finally I've found some time to fix it for good.
> flang2: handle atomic load of logical variables of various size correctly

- runtime/flang/miscsup_com.c
- test/f90_correct/inc/intrinsic_nearest.mk
- test/f90_correct/lit/intrinsic_nearest.sh
- test/f90_correct/src/intrinsic_nearest.f90
When the 1st parameter is positive or negative infinity, the intrinsic function `NEAREST` wrongly returns the same value while it should return the positive or negative number of the largest magnitude accordingly when the 2nd parameter has the different sign.
This patch fixes this bug by adding logic to handle the aforementioned situations for all single-, double-precision fp numbers.
> Fix the bug that NEAREST returns wrong value for +/- infinity.

- test/f90_correct/inc/data_char.mk
- test/f90_correct/lit/data_char.sh
- test/f90_correct/src/data_char.f90
- tools/flang2/flang2exe/llassem.cpp
- tools/flang2/flang2exe/llassem.h
- tools/flang2/flang2exe/llassem_common.cpp
- tools/flang2/flang2exe/llassem_common.h
Fix the bug while using DATA, the test case is as following:
```Fortran
program p
character*6 a
character*10 b
character*10 c
data a(2:5) /'AAA'/
data b(3:6) /'BBB'/
data b(8:9) /'CC'/
data c(3:5) /'345'/
data c(6:9) /'6789'/
print *, "a = ", a
print *, "b = ", b
print *, "c = ", c
end
```
After using data to append string, Fortran expected results should be:
```
a = ' AAA  '
b = '  BBB  CC '
c = '  3456789 '
```
But the flang print incorrect result for using 0x00 in ASCII code as space.
The outputs as following:
```
a = ' AAA '
b = ' BBB CC'
c = ' 3456789'
```
> Fix issue of processing character variables via the DATA statement.

- include/legacy-util-api.h
- lib/scutil/path-utils.c
- tools/flang1/flang1exe/accpp.c
- tools/flang1/flang1exe/dinit.c
- tools/flang1/flang1exe/dinitutl.c
- tools/flang1/flang1exe/fpp.c
- tools/flang1/flang1exe/interf.c
- tools/flang1/flang1exe/lower.c
- tools/flang1/flang1exe/lowerilm.c
- tools/flang1/flang1exe/main.c
- tools/flang1/flang1exe/module.c
- tools/flang1/flang1exe/scan.c
- tools/flang1/flang1exe/semutil2.c
- tools/flang1/flang1exe/xref.c
- tools/flang2/flang2exe/dinit.cpp
- tools/flang2/flang2exe/dinitutl.cpp
- tools/flang2/flang2exe/main.cpp
- tools/flang2/flang2exe/xref.cpp
`tmpf` is a wrapper for `tmpfile(3)`, which is declared in stdio.h. `tmpf` accepts and ignores a string argument, and in all uses of the function, string literals are passed to it. This has caused a `-Wunused-parameter` warning and multiple `-Wincompatible-pointer-types-discards-qualifiers` or `-Wwritable-strings` warnings.
Since the wrapper doesn't seem to serve any purpose, we should just delete it and use `tmpfile` directly.
> [scutil] Delete tmpf and use tmpfile instead; NFC

- tools/shared/utils/common/utils.cpp
We have a drive letter before the first path separator on Windows.
> win: fix include path check

- test/f90_correct/inc/size_intrin.mk
- test/f90_correct/lit/size_intrin.sh
- test/f90_correct/src/size_intrin.f90
- tools/flang1/flang1exe/ast.c
- tools/flang1/flang1exe/outconv.c
Please consider below testcase
```````````````````
program test
integer:: arr (1:10) = 0
integer :: s1=1
integer :: arrsize
arrsize = size (arr(10:1:-s1),1)
print *, arrsize
program test
```````````````````
which gives zero as result in place of expected 10.
The flang1 generates
```````````````````
i0: BOS l5 n1 n0
i4: FILE n5 n1 n1000
i8: BASE s629
i10: BASE s628
i12: ILD i10
i14: INEG i12
i16: ITOI8 i14
i18: KCON s631
i20: KADD i16 i18
i23: KDIV i20 i16
i26: KCON s610
i28: KCON s612
i30: KCON s627
i32: KCMP i28 i30   !<------ compares lowerbound and upperbound
i35: GE i32
i37: KMERGE i23 i26 i35  !<-- return i26 (zero) in case lb > ub,
!   which is wrong in case of negative stride
i41: I8TOI i37
i43: IST i8 i41
```````````````````
i32 should compare i23 against zero.
This code is …
> [flang1] Fix inline code for size intrinsic for negative strides.

- runtime/flang/global.h
These functions are superfluous, we don't need to use them
on Windows.
> win: Remove unused function declarations

- .github/workflows/build_flang.yml
CI workflow for release_11x and release12x still enabled, Flang workflow not broken
> Removing CI build workflow for release_100 from classic-llvm-flang

- tools/flang2/flang2exe/main.cpp
- tools/shared/ccffinfo.c
- tools/shared/ccffinfo.h
- tools/shared/fih.h
The string parameters in the common compiler feedback format (CCFF) APIs are never modified, and many of them are called with string literals as arguments. Declaring the parameters `const char *` eliminates a number of `-Wcast-qual` and `-Wwritable-strings` warnings.
> [CCFF] Use const char * in CCFF APIs; NFCI

- runtime/flang/global.h
The build is broken with a redefinition error:
typedef redefinition with different types
('__INT_T' (aka 'long') vs 'int')
typedef __INT_T INT;       /* native integer at least 32 bits */
'INT' is already defined in winnt.h as 'int'.
The comment says it needs a 'native integer at least 32 bits',
'int' should be fine for it on all platform.
> win: Fix the build on Windows

- test/sema/aconst_with_null_subict.f90
The test case `test/sema/aconst_with_null_subict.f90` was writing a `.qdbf` file to the source directory unnecessarily. This patch stops it from doing so.
> [test] Stop writing to source directory; NFC

- runtime/include/FuncArgMacros.h
We can use standard symbol names, it seems it is not
necessary to keep different symbol names for Windows.
> Remove Fortran entry symbol formats for Windows

- test/f90_correct/inc/use01.mk
- test/f90_correct/inc/use02.mk
- test/f90_correct/inc/use03.mk
- test/f90_correct/inc/use04.mk
- test/f90_correct/inc/use05.mk
- test/f90_correct/inc/use06.mk
- test/f90_correct/lit/use01.sh
- test/f90_correct/lit/use02.sh
- test/f90_correct/lit/use03.sh
- test/f90_correct/lit/use04.sh
- test/f90_correct/lit/use05.sh
- test/f90_correct/lit/use06.sh
- test/f90_correct/src/use01.f90
- test/f90_correct/src/use02.f90
- test/f90_correct/src/use03.f90
- test/f90_correct/src/use04.f90
- test/f90_correct/src/use05.f90
- test/f90_correct/src/use06.f90
- tools/flang1/flang1exe/module.c
- tools/flang1/flang1exe/semant.c
- tools/flang1/flang1exe/semsym.c
- tools/flang1/utils/prstab/gram.txt
The reason of the problem is that the symbols with the same name
in different modules are linked in the hash list, and the local symbol is
inserted in front of the matching symbol instead of the head of hash list.
This commit adds an existence check of rename to fix the problem.
> Fix for the issue #1146 introduced by PR #949(issue #889).

- tools/flang2/flang2exe/cgmain.cpp
- tools/flang2/flang2exe/llutil.h
Commits 4c6964dabf06, 2838f5dbdc58, and 255fce7a3bf5 have re-written how loop metadata are generated for `NODEPCHK` and `VECTOR ALWAYS` directives. As a result, the `mark_rw_nodepchk` function from the original implementation is no longer called, which means the `rw_nodepchk` flag is never true, causing some code to never run. In particular, the unused `mark_rw_nodepchk` function causes `-Werror` to fail the build. This patch deletes all the dead code, merges `cons_no_depchk_metadata` into `cons_vec_always_metadata` (both are identical) and fixes up some incorrect comments.
> [flang2] Delete dead loop metadata code and fix build error on master branch; NFCI

- test/directives/novector.f90
- test/directives/omp_simd_clause.f90
- test/directives/prefetch.f90
- test/directives/unroll.f90
- test/directives/vector.f90
This is re-upload of PR #1152 which introduces two version of the prefetch test case. I decided to introduce separate version for LLVM13 (and later!) instead of turning a good test case into worse for a sake of backward compatibility.
> Adding changes to tests files to adapt to LLVM13 rules.

- test/debug_info/usemodule.f90
- tools/flang1/flang1exe/lowersym.c
- tools/flang1/flang1exe/module.c
- tools/flang1/utils/symtab/symtab.n
- tools/flang2/flang2exe/cgmain.cpp
- tools/flang2/flang2exe/upper.cpp
- tools/flang2/utils/symtab/symtab.n
Currently ILM file generated by Flang1 does not distinguish between
below two casese
1. Renamed use
use mymod, var_z => var_y
2. Restricted and renamed use
use mymod, ONLY: var_z => var_y
In both the cases debug info generated for case-2.
Please consider below testcase
``````````````````````` 
module mod1
integer :: var_x = 30, var_y = 31
real :: var_f = 30.1
end module mod1
program p1
use mod1,var_z => var_x ! rename var_x with var_z, unable to access var_y now in gdb
integer::aa=100
print *,var_z
end
```````````````````````
Without this patch, Flang generated binary behaves inside debugger as
```````````````````````
gdb) print var_y^M
No symbol "var_y" in current context.
```````````````````````
Now Flang1 is modified to preserve restricted use status in f62 and Flang2 preserves in f95. …
> [DebugInfo] Missing debug info when one of the module variable is renamed

- test/debug_info/use_only_test.f90
- test/debug_info/use_only_test.f90_mod.f90
- tools/flang2/flang2exe/lldebug.cpp
Please consider below testcases.
use_only_test.f90_mod.f90
````
module use_only_mod
integer :: mod_var = 10
end module use_only_mod
````
use_only_test.f90
````
program main
use use_only_mod, only: mod_var
implicit none
print*, mod_var
end
````
Without this patch, executable behaves inside debugger as
````
Breakpoint 1, main () at use_only_test.f90:4
4         print*, mod_var
(gdb) p mod_var
No symbol "mod_var" in current context.
````
> [DebugInfo] Debug support for module defined in a different file

- runtime/flang/descIntrins.c
- runtime/flang/entry.c
- runtime/flang/fioMacros.h
- runtime/flang/initpar.c
- runtime/include/FuncArgMacros.h
Set the proper prefix for the delcarations.
> win: Fix the inconsistent usage of dllexport/dllimport

- runtime/flang/CMakeLists.txt
Needs to use '/fp:fast' [1] compiler option instead.
[1]: https://docs.microsoft.com/en-us/cpp/build/reference/fp-specify-floating-point-behavior?view=msvc-160#fast
> win: 'ffast-math' option is not recognized by clang-cl

- test/f90_correct/inc/format_specification.mk
- test/f90_correct/lit/format_specification.sh
- test/f90_correct/src/format_specification.f90
- tools/flang1/flang1exe/scan.c
The following test case is generated from the workload WAVEWATCH III 6.07.1 (https://github.com/NOAA-EMC/WW3) and CMAQ 4.7.1 (https://github.com/USEPA/CMAQ).
```
program example
integer :: i = 1, j = 2, k = 3
character(len=2) :: expect(3) = (/'1 ', ' 2', ' 3'/)
character(len=2) :: res
write(res, 10) i
if (res .ne. expect(1)) stop 1
write(res, 20) j
if (res .ne. expect(2)) stop 2
write(res, 30) k
if (res .ne. expect(3)) stop 3
print *, 'PASS'
10 FORMAT (I0)
20 FORMAT (I02)
30 FORMAT (I2)
end
```
In format specification, the token type TK_G0FORMAT is for I0, not for I02 or I002, or something like that. Fix the token pattern matching of TK_G0FORMAT by checking if the next identifier of '0' in id buffer is null.
> [flang1] Fix bug in TK_G0FORMAT token pattern matching (encountered in workloads WAVEWATCH III and CMAQ)

- tools/flang2/utils/upper/CMakeLists.txt
clang-cl doesn't recognize "-P -E -x c" compiler arguments,
we should use MSVC version of them "/E /TC".
Seems clang-cl is not able to handle /P /E together
so I only left the necessery one.
Fixes: #1192
> win: Fix upperilm header generation

- runtime/libpgmath/lib/generic/math_tables/CMakeLists.txt
- runtime/libpgmath/lib/x86_64/math_tables/CMakeLists.txt
Emulating touch command reduces the external build dependency,
especially on Windows where 'touch' is not available by default.
> Use cmake built-in touch command instead of native one

- test/sema/interface_nested_into_subroutine.f90
- tools/flang1/flang1exe/interf.c
- tools/flang1/flang1exe/module.c
It's my proposal for fix for ticket
https://trello.com/c/V7wB3kC6/30-hpcl3-1205-bigdft-surprising-interactions-within-the-code-interface-nested-into-subroutine-causes-imported-symbol-appear-undefin
related to
https://github.com/flang-compiler/flang/issues/1013
More experienced devs - please share discussion about pros and cons of such solution, because I can be wrong- this is only my idea and i can not investigate it deeper without any comments from you of such solution.
Please pay attention mostly because I am afraid that this fix will put regression- will let to successfully compile the programs which should not.
> interface nested into subroutine causes symbol undefined, fix #1013

- lib/scutil/host-fp-folding.c
- runtime/flang/async.c
- tools/flang2/flang2exe/upper.cpp
* Avoid to build x86_64 intrinsics for ARM.
* Use general Windows macro instead of x86_64 specific.
> win: Fix the build on Windows on ARM

- runtime/flang/allo.c
- test/f90_correct/inc/implied_do1.mk
- test/f90_correct/lit/implied_do1.sh
- test/f90_correct/src/implied_do1.f90
- tools/flang1/flang1exe/semutil2.c
- tools/shared/rtlRtns.c
- tools/shared/rtlRtns.h
When an implied-do loop in an array constructor contains in its value list a function call that returns an array, flang at present handles the function call once outside the loop and then inserts the returned values into the final array repeatedly during the loop, causing wrong result.
This patch fixes the bug by invoking the function and inserting the results in each iteration of the loop.
> Fix bugs pertaining to an array constructor with an implied-do containing an expression that is a function call returning an array.

- test/llvm_ir_correct/fypp-dilocation.f90
- tools/flang2/flang2exe/lldebug.cpp
CP2K uses fypp, a Fortran preprocessor based on Python expressions. It
can generate large code blocks spanning several functions from a
single line directive. This severely confuses flang's lldebug routines
making them unable to emit DILocation nodes (e.g. for the loops).
The consequences of this can vary, the most visible is an assertion
failure experienced while building CP2K with -g flag using
an assertion-enabled compiler.
The patch presented in this PR fixes the issue.
> [debuginfo] solve issues with DILocation nodes not being generated for the CP2K sources

- .github/workflows/build_flang.yml
There is a CI error for release_11x branch. While discussing we came to the conclusion that no one is using release_11x and hence it is safe to remove from CI. Also adding release_13x.
> Remove CI testing of release_11x and add release_13x 

- test/debug_info/allocated_nodup.f90
- test/debug_info/procedure_pointer.f90
- test/debug_info/procptr_ptrarg.f90
- test/debug_info/scalar_allocatable.f90
- tools/flang2/flang2exe/cgmain.cpp
- tools/flang2/flang2exe/cgmain.h
- tools/flang2/flang2exe/lldebug.cpp
- tools/flang2/flang2exe/lldebug.h
Please consider below test
`````````
program test
interface
subroutine sub (sarg)
real :: sarg
end subroutine
end interface
procedure(sub), pointer:: gsubptr => NULL()
gsubptr => sub
call gsubptr (2.5)
end program test
subroutine sub (a)
real :: a, res
res = 2.1 * a
print *, res
end subroutine
`````````
After the patch (inside debugger)
`````````
10        call gsubptr (2.5)
(gdb) pt gsubptr
type = PTR TO -> ( void () (real) )
`````````
Prerequisite for this PR is : https://github.com/flang-compiler/flang/pull/1140 (first commit of current PR)
> [DebugInfo] Debug support for procedure pointer

- runtime/flang/close.c
- runtime/flang/utils.c
Commit d3ee7f250c0331f7381d6bffe7b40037304f275e made the "name" field
in FIO_FCB objects a pointer to malloc'ed memory in all cases. When
freeing a FIO_FCB object, the name should be freed in all cases as well.
> [runtime] Fix memory leak when freeing FIO_FCB

- test/debug_info/assumed_len.f90
- tools/flang2/flang2exe/cgmain.cpp
- tools/flang2/flang2exe/cgmain.h
- tools/flang2/flang2exe/lldebug.cpp
This fix handle support for Assumed length string type during debug info
generation. It emits !DIStringType metadata with stringLength field, which
points to compiler generated local variable(metadata !28 below) and holds
the length of assumed string. This fix has dependency on LLVM11 and above
to emit DW_AT_string_length attribute.
snippet from flang generated IR :
. . .
call void @llvm.dbg.declare (metadata i64* %.U0001.addr, metadata !28, metadata !29), !dbg !26
. . .
!28 = !DILocalVariable(scope: !25, arg: 2, file: !3, type: !27, flags: 64)
!29 = !DIExpression()
!30 = !DIStringType(name: "character(*)!2", size: 32, stringLength: !28, stringLengthExpression: !29)
. . .
Sample Dwarf info generated with flang fix:
. . .
0x0000009d:   DW_TAG_string_type [9]
DW_AT_name [DW_FORM_strp] …
> [DebugInfo] flang support for Assumed length string type

- tools/flang2/flang2exe/ll_structure.cpp
This patch fixes a very well hidden bug: va_list variable ap
was used before va_start() was called.
According to Robert Lipe, it is safe to call va_start()/va_end()
pair multiple times:
```
The standard doesn't appear to forbid it. In the non-normative text
of Plauger's "The Standard C Library" it says "Once ou execute va_end
you must not again execute va_arg unless you first execute va_start to
initiate a rescan."    This appears to give extra credence to the
restartability.
```
see https://gcc.gnu.org/legacy-ml/gcc/2001-08/msg00478.html
> [flang2] fix va_list being used before va_start() was called

- test/preprocessor/dm_option.f90
- tools/flang1/flang1exe/accpp.c
- tools/flang1/flang1exe/flgdf.h
- tools/flang1/flang1exe/fpp.c
- tools/flang1/flang1exe/global.h
- tools/flang1/flang1exe/main.c
It was decided to add clang -dM option to flang.
It prints out all the macros defined - similarly as clang or gfortran does it.
It works only with llvm PR for this : https://github.com/flang-compiler/classic-flang-llvm-project/pull/90
> Introduce the -dM option to print out the compiler-defined macros

- runtime/flang/iso_fortran_env.f90
- tools/flang1/flang1exe/semutil2.c
After #1129 commited, a regression is generated when compiling OpenMPI. 
_Originally posted by @pawosm-arm in https://github.com/flang-compiler/flang/issues/1129#issuecomment-1030595159_
This PR fix this issue by correctly declaring REAL128 kind parameter.
> [runtime] Fix bug in iso_fortran_env.f90 (encountered in OpenMPI)

- test/f90_correct/inc/proc_ptr.mk
- test/f90_correct/lit/proc_ptr.sh
- test/f90_correct/src/proc_ptr.f90
- tools/flang1/flang1exe/exterf.c
When exporting a procedure, if `PARAMCT` is not positive (e.g., when a name of a function is used as the procedure interface in a procedure declaration statement before the function is defined and later the function declartion statement has a `RESULT` clause
and zero dummy arguments, `PARAMCT` will be 0), then it should be illegal to access the beginning of the argument list of the function. zero or negative  Failing to prevent this kind of illegal access will cause a segmentation fault.
This patch fixes the bug by checking whether `PARAMCT` is greater than 0 before accessing the argument list.
> Prevent illegal argument accessing during procedure exporting.

- test/f90_correct/inc/alloc_unpoly_str_01.mk
- test/f90_correct/inc/alloc_unpoly_str_02.mk
- test/f90_correct/lit/alloc_unpoly_str_01.sh
- test/f90_correct/lit/alloc_unpoly_str_02.sh
- test/f90_correct/src/alloc_unpoly_str_01.f90
- test/f90_correct/src/alloc_unpoly_str_02.f90
- tools/flang1/flang1exe/semant3.c
It also fixes the length parameter not being correctly assigned problem mentioned at the end of issue #713.
This patch piggybacks the logic to handle source-allocating a class(*) array from an array of deferred length character strings on the code handling source-allocating an unlimited_polymorphic array from a string.
> Fix the ICE caused by source-allocating a class(*) array from an array of deferred length character strings. See issue #713.

- test/debug_info/deferred_len.f90
- tools/flang2/flang2exe/cgmain.cpp
- tools/flang2/flang2exe/lldebug.cpp
This fix handle support for Deferred length string type during debug info
generation. Here the length of the string is available during runtime only
and its part of array descriptor ($sd), its 4th field as shown below where
the length of the sample string taken is 6
array_descriptor = (14, 140737341741098, 0, 6, 3, 140737354099760, 498, 140737341742316, 0, 140737323837350, 3, 22, 0, 140737341514576, 0, 140737354129776)
This fix extracts the length field from array descriptor and creates a local
variable to hold this length. Here DIExpression used will extract the length
which is 24 bytes or 0x18 bytes away from the start of the array descriptor.
DIStringType with stringLength attribute is generated. stringLength will point
to this local variable which holds the length field. This fix has …
>  [DebugInfo] flang support for Deferred length string type

- runtime/flang/pack.c
- test/f90_correct/inc/intrinsic_pack.mk
- test/f90_correct/lit/intrinsic_pack.sh
- test/f90_correct/src/intrinsic_pack.f90
- tools/flang1/flang1exe/semfunc.c
1. When the mask is a scalar false and the vector arg is absent, `PACK` wrongly returns an array of the same size as the array arg with all elements being the zero value, while it should return an empty array. This happens because the size of the result is calculated wrongly in the particular situation and the patch fixes it by giving the correct size for the result.
2. When the mask is a scalar false but the vector arg is given, `PACK` returns an array of the same size as the vector but all elements being zero, while the elements should have the same value and in the same order as the vector. This bug is caused in the runtime lib code for the intrinsic function `PACK` where it doesn't collect vector elements and returns too early when the the mask is a false scalar value. This patch …
> Fix 2 bugs of PACK when the mask arg is a scalar of false

- test/debug_info/common.f90
- tools/flang2/flang2exe/lldebug.cpp
Currently a debug metadata of artificial global variable type for common block is generated (in addition to user visible common block members). With Flang extension of LLVM it has no name, otherwise it has name. Both the cases are problematic and redundant. which should be removed.
Please consider below test case.
```
program main
integer :: cvar1, cvar2
common /cname/ cvar1, cvar2
cvar1 = 1
cvar2 = 2
print *, cvar1
print *, cvar2
end program main
```
Generated IR.
```
!1 = distinct !DIGlobalVariable(name: "cvar1", scope: !2, file: !4, type: !16, isLocal: false, isDefinition: true)
!2 = distinct !DICommonBlock(scope: !3, declaration: !9, name: "cname")
!8 = !DIGlobalVariableExpression(var: !9, expr: !DIExpression())
!9 = distinct !DIGlobalVariable(scope: !2, type: !10, isLocal: false, …
```
> [DebugInfo] Artificial var debug info for common block should not be gererated

- test/f90_correct/inc/array_constructor01.mk
- test/f90_correct/lit/array_constructor01.sh
- test/f90_correct/src/array_constructor01.f90
- tools/flang1/flang1exe/semutil2.c
When the size of any dimension of array section in array constructor is a variable or
a constant whose value is greater than the macro THRESHHOLD, all dimensions should be treated as deferred dimensions.
> Fix issue #1227 about array constructor

- test/f90_correct/src/im30.f
LLVM15+ brings a new default for creation of the PIE binaries on Linux
systems. In effect, position independed executables are always
assumed.
With the recent change in the default for creation of PIE binaries,
some of the fragile test cases could start to fail.
In the im30 test case, the result of the first use of %loc() function
was truncated (due to the way the variable holding the result is
created), while the second use of %loc() was properly used (in the
comparison expression) as a 64-bit value. Up until recently it wasn't
hurting as the most significant bits were always 0. Sadly, it has
changed with the introduction of the PIE binaries.
Due to the way the `locf` array is created, we have no ability to
change its assumed type. In order to keep this test objectives intact,
the result …
> Fix the im30.f test case

- test/debug_info/allocated_nodup.f90
- test/debug_info/cmn_blk_dbg_info.f90
- test/debug_info/debug_module_import.f90
- tools/flang2/flang2exe/llassem.cpp
- tools/flang2/flang2exe/llassem.h
Issue: Common block variables are shown as “optimized out” in subroutines. (Due to missing metadata references).
Fix: In the  “write_comm” function, instead of emitting the global variable with defn to IR, we capture the same into a member “cmblk_init_data” of variable agb.  At the end of processing a source file, in the function “assemble_end”, we will generate the same with all the debug info metadata references.
Note: This is same as #1169. Review comments are addressed here.
> [DebugInfo] Display common block variable in sub-routines

- test/f90_correct/inc/move_alloc.mk
- test/f90_correct/lit/move_alloc.sh
- test/f90_correct/src/move_alloc.f90
- tools/flang1/flang1exe/semutil2.c
This is not the best solution for this problem. But it's the one that does not require a major rewrite of the code in this area.
The Fortran's internal move_alloc() subroutine failed to accept more complex field selection expressions used for the subroutine parameters. This patch solves the problem by adding more eager traversal through the member selection expression.
> Fix lowering of move_alloc() subroutine

- test/f90_correct/inc/poly_ptr_to_str_1.mk
- test/f90_correct/inc/poly_ptr_to_str_2.mk
- test/f90_correct/lit/poly_ptr_to_str_1.sh
- test/f90_correct/lit/poly_ptr_to_str_2.sh
- test/f90_correct/src/poly_ptr_to_str_1.f90
- test/f90_correct/src/poly_ptr_to_str_2.f90
- tools/flang1/flang1exe/symutl.c
This patch fixes the bug in polymorphic string pointer when the polymorphic variable is a derived member.
```
program poly_ptr_to_str_2
type t
class(*), pointer :: val
end type t
type(t) :: x
character(3), target :: a = 'foo'
character(:), pointer :: b
character(:), allocatable :: s
b => a
x%val => b
select type (val => x%val)
type is (character(*))
s = val
end select
end
```
The statements are dumped with breakpoint set at function `lower` as follows:
```
(gdb) b lower
...
(gdb) p dsstds(0,0)
subprogram 1 poly_ptr_to_str_2:
std:1    ast:22    lineno:17          b$sd(4_8) = 3_8
std:2    ast:23    lineno:17          call .ptr2_assign(b,b$sd,a,14_8,0_8)
std:3    ast:34    lineno:18          x%val$sd(4_8) = len(b)
std:21   ast:84    lineno:18          if (loc(x) .ne. 0_8) call …
```
> [flang1] Fix bug in poly str pointer

- tools/flang1/flang1exe/semutil2.c
The dangling else problem was found to cause some failures in
a proprietary test suite.
> Add explicit braces to avoid dangling else problem

- tools/flang2/utils/upper/CMakeLists.txt
The CMake recipe for running `upperl` to generate `upperilm.h` from `upperilm.in` incorrectly leaves out a terminating newline character, without which the parser inside `upperl` will not print the last opcode (`IM_KXOR`, a.k.a. `XOR8`) in its output. This patch adds back the missing newline and fixes the `XOR8` opcode.
> [flang2] Fix generation of upperilm.h

- test/f90_correct/inc/arr01.mk
- test/f90_correct/lit/arr01.sh
- test/f90_correct/src/arr01.f90
- tools/flang1/flang1exe/semant.c
When a named constant array is declared as a deferred shape array, flang1 only reports the error without setting the array in a proper state, leading to the ICE afterwards.
This patch fixes the ICE by recovering the array as a zero-sized array.
> Fix an ICE occurring when a named constant array is declared deferred shape.

- test/f90_correct/inc/empty_type_01.mk
- test/f90_correct/lit/empty_type_01.sh
- test/f90_correct/src/empty_type_01.f90
- tools/flang1/flang1exe/dinit.c
- tools/flang1/flang1exe/dtypeutl.c
- tools/flang1/flang1exe/dtypeutl.h
- tools/flang1/flang1exe/semutil2.c
- tools/flang2/flang2exe/dinit.cpp
- tools/flang2/flang2exe/dtypeutl.cpp
- tools/flang2/flang2exe/dtypeutl.h
- tools/flang2/flang2exe/llassem.cpp
The problem occurs：
1.When an array constructor with an empty structure constructor is passed as an argument to a function，flang2 will generate wrong IR to use an undefined type named 'struct.STATICS*';
2.When an array constructor has several empty structure constructors, semantic analysis handling the empty structure construct will be prevented with bogus error "F90-S-0069-Illegal implied DO expression".
This patch fixes the 1st bug by skipping over unnecessary processing when the element type is an empty drived data type in flang2. This patch fixes the 2nd bug by not processing the components in the function `dinit_data` from file 'dinit.c' and returning the real ACL pointer instead of 0 in `rewrite_acl` from file 'semutil2.c'.
> Fix errors related to empty structure constructors nested in an array constructor.

- test/debug_info/deferred_len.f90
- test/debug_info/deferred_len_in_module.f90
- tools/flang2/flang2exe/lldebug.cpp
This patch extends support to deferred array in global
scope (i,e inside modules).
Follow the same design as local deferred length arrays and
create a new global variable mdnode to capture the length of
the array.
Module deferred array variable considered as string type will
refer above mdnode to find the string length (length of array).
> Support debug info for deferred array in module.

- runtime/libpgmath/lib/common/ceil.c
- runtime/libpgmath/lib/x86_64/math_tables/mth_ceildefs.h
This was noticed in https://github.com/flang-compiler/flang/pull/1120, but decided to implement as a separate PR.
cc @d-parks
> add missing ceil avx, sse functions

- test/llvm_ir_correct/invalid_ambiguous_generic_proc.f90
- test/llvm_ir_correct/invalid_public_entity_error.f90
Initially, I could not replicate this error outside the testing
environment. Then I figured out that both these tests share the
same names of the exported modules. In effect, two flangs running
in parallel are overwritting the same .mod files.
This patch renames the modules so they are different for each test.
> Make those two tests safe to run in parallel

- test/llvm_ir_correct/final-subroutine.f90
- tools/flang1/flang1exe/semtbp.c
As Fortran 2018 7.5.6.1 NOTE 1, final subroutines are effectively always
"accessible". So, the final subroutine can never be private.
> [flang1] Fix final subroutine attribute

- runtime/libpgmath/lib/common/dispatch.c
The disputed SLEEP() macro is never used in the libpgmath code for Linux.
Deleted here in order to prevent potential future use of sleep() function
not recommended due to potential messing with SIGALRM.
Note that non-Windows libpgmath code already uses nanosleep() for
sleeping, which is recommended.
> libpgmath sanity: do not call sleep() in Linux systems

- test/debug_info/nametable.f90
- test/debug_info/producer.f90
- test/debug_info/redundant_inst.f90
This PR is a series of the 3 small commits.
The LLVM14 uses dwarf version 5 by default, but those tests are only compatible with the older dwarf version.
> Set dwarf version to 4 in debug_info tests

- runtime/CMakeLists.txt
E.g. TARGET_LINUX_ARM64 is being used, so it is worth to make sure it is explicitly defined.
> runtime, NFCI: fix inconsistency in defining 64-bit ARM architecture

- test/lit.cfg
When flang is being built with compiler version newer than
the one installed on the system, we need to make sure that
COMPILER_PATH variable is set for lit testing,
otherwise there might be compatibillity problems with the libgcc.a library.
Flang tests are building and executing programs, so some symbols
could be missing when those programs are linked with older libgcc.a
than the one used to build compiler.
> Fix flang testing with newer gcc versions

- tools/flang2/flang2exe/cgmain.cpp
The goal is to have all of those `LL_MDRef` objects being initialized the same way.
This is to prevent `cached_access_grop_metadata` being used uninitialized in the functions like `cons_loop_parallel_accesses_metadata()`.
> NFCI: improve consistency by explicitly initializing cached_access_group_metadata

- tools/flang1/flang1exe/astout.c
- tools/flang1/flang1exe/exterf.c
- tools/flang1/flang1exe/fpp.c
- tools/flang1/flang1exe/gbldefs.h
- tools/flang1/flang1exe/inliner.c
- tools/flang1/flang1exe/interf.c
- tools/flang1/flang1exe/module.c
- tools/flang2/flang2exe/gbldefs.h
Despite the changes introduced by commit
c9c3f0d0479744c336c45daaa635f33284c93ca8
...we're still experiencing issues while compiling Fortran codes deep
in the directory tree.
> flang1, flang2: larger buffers, to hold longer filenames

- test/f90_correct/inc/protected.mk
- test/f90_correct/lit/protected.sh
- test/f90_correct/src/protected.f90
- tools/flang1/flang1exe/semfunc2.c
- tools/flang1/flang1exe/semutil.c
A syntactical error should be reported when a dummy argument is specified with `INTENT(out)` or `INTENT(inout)` while the actual argument has the attribute `PROTECTED`.
A syntactical error should be reported when modifying a `PROTECTED` pointer variable.
This patch catches and reports 2 new grammar errors related to the `PROTECTED` parameter (and extends the buffer for the error message):
1.A use-associated object with the `PROTECTED` attribute cannot be an actual argument when the dummy argument
2.A use-associated object with the `PROTECTED` attribute cannot be assigned
> Add reporting for two grammar errors pertaining to PROTECTED attribute.

- runtime/flang/alarm3f.c
Popular UNIX systems (e.g. Linux, MacOS) have alarm() function
declared in unistd.h, there is no need to provide a separate forward
declaration, which could go easily out of date and create a conflict
at compile time.
> runtime: fix building of alarm3f.c on Linux systems with modern glibc

- test/directives/vector_directive3.f90
An early attempt of using LLVM15 encountered just one failure
> tests: fix test case failing after attempted use of LLVM15

- test/driver/ieee_mode.f90
To make this pass, https://github.com/flang-compiler/classic-flang-llvm-project/pull/122 (and similar for other LLVM release branches) needs to be merged first.
> tests: The IEEE mode is now being used by default

- test/f90_correct/inc/implied_do10.mk
- test/f90_correct/inc/implied_do11.mk
- test/f90_correct/lit/implied_do10.sh
- test/f90_correct/lit/implied_do11.sh
- test/f90_correct/src/implied_do10.c
- test/f90_correct/src/implied_do10.f90
- test/f90_correct/src/implied_do11.f90
- test/sema/implied_do.f90
- tools/flang1/flang1exe/semutil2.c
After PR#1212 commited, @paulwalker-arm found a test case failed and filed a issue https://github.com/flang-compiler/flang/issues/1253, this PR is used to fix this regression.
In https://github.com/flang-compiler/flang/pull/1102, [qiaozhang-hnc](https://github.com/qiaozhang-hnc) introduced a zero-size array to handle a function which return an array in impiled-do statement, and then call `realloc` to get the right size of array.
In #1212, I called `move_range_after()` to change the order of stmts . However, it is not well coordinated with #1102, resulting in the problem of undefined use.
> [flang1] Fix the issue which introduced form PR#1212

- test/f90_correct/inc/empty_type_02.mk
- test/f90_correct/lit/empty_type_02.sh
- test/f90_correct/src/empty_type_02.f90
- test/sema/sconst_with_null_subc.f90
- tools/flang1/flang1exe/exterf.c
- tools/flang1/flang1exe/interf.c
- tools/flang1/flang1exe/interf.h
The root cause is that when an empty derived type parameter is declared in module,
an ACL structure for that parameter is generated, but its subc node is empty and
exported to the MOD file. But when importing the MOD file, flang cannot get the
information of this empty subc node.
This commit adds a flag to the MOD file to indicate whether the ACL structure
for the derived type parameter has a subc node.
> Fix for regression introduced by PR #1101.

- runtime/include/komp.h
Afaict, `__WORDSIZE` is only defined on glibc (and XCode?) platforms.
This change should fix compilation for MinGW.
> portability: `__WORDSIZE` isn't defined in MinGW

- runtime/include/komp.h
On platforms with LLP64 data model (e.g. Windows 64-bit), `long` has 4 bytes. Use `kmp_int64` (a typedef for `long long`) to fix alignment and size of `kmp_critical_name` on such platforms (to match the comments).
> portability: Fix alignment and size for LLP64

- .github/workflows/build_flang.yml
- .github/workflows/build_flang_arm64.yml
The GitHub workflow should stop building with the release_11x branch. This will unblock PRs that require newer versions of LLVM.
> [build] Update workflows to build release_13x and release_14x

- test/f90_correct/inc/rio2.mk
- test/f90_correct/inc/rio3.mk
Previously, classic flang provides ompstub for cases using openmp
runtime routines, but not adding the option "-fopenmp". gfortran/ifort
report errors of "undefined reference to ...".
This adds the option "-fopenmp" for the two test cases, which is
prepared for removing the "-lompstub" in the driver. After that, the two
test cases compiled without the option "-fopenmp" will report the error.
> [NFC] Add -fopenmp to test cases which use openmp runtime routines

- test/f90_correct/inc/func_result.mk
- test/f90_correct/lit/func_result.sh
- test/f90_correct/src/func_result.f90
- tools/flang1/flang1exe/semant.c
This patch fixes the following bugs:
- When declaring the result variable with the `PARAMETER` attribute, flang doesn't raise an error, causing segmentation fault downstream.
- When initializing the result variable at the time of declaration, flang reports a wrong error.
- When the result variable collides with the name of a derived type, flang doesn't raise an error, causing ICE downstream.
> Fix improper handling of errors caused by invalid declaration of result variable

- test/f90_correct/inc/en02.mk
- test/f90_correct/lit/en02.sh
- test/f90_correct/src/en02.f90
- tools/flang1/flang1exe/semant3.c
Flang doesn’t catch and handle the syntax error that the name of an entry point is used as an argument when a result clause is present, ultimately causing a segmentation fault in flang2. This patch fixes the issue by catching and reporting the syntax error described above. It then restores the right state.
> Fix the bug where the name of ENTRY is used as an argument

- test/f90_correct/inc/assumed_len_char_01.mk
- test/f90_correct/lit/assumed_len_char_01.sh
- test/f90_correct/src/assumed_len_char_01.f90
- tools/flang1/flang1exe/semfunc.c
- tools/flang1/flang1exe/semutil.c
- tools/flang1/flang1exe/semutil2.c
- tools/flang2/flang2exe/exp_rte.cpp
- tools/flang2/flang2exe/lldebug.cpp
When an assumed length character function is not external,  its symbol type will at first be set to `ST_IDENT` and the `AUTOBJ` field will be set to `1`. When a invocation of it is encountered, its symbol type will be modified to `ST_PROC`. But its `AUTOBJ` 
remains `1` which will causes a segmentation fault later.
This patch fixes the issue by removing the function from the automatic data list and setting its `AUTOBJ` to `0`.
The other issue is that flang sets the return length as `0` for assumed length character functions, causing an ICE afterwards.
This patch fixes it by modifying the ast type of the function (from ‘A_FUNC’ to `A_CALL`), and adding code to process the argument for the length.
> Fix a segmentation fault related to assumed length character functions.

- test/debug_info/assumed_shape_non_contiguous.f90
- tools/flang2/flang2exe/ll_write.cpp
- tools/flang2/flang2exe/lldebug.cpp
In existing debug info subscript is defined as lowerBound/upperBound/stride,
lowerBound is constant and upperBound is DIVariable and stride is taken from
descriptor. At higher optimizations DIVariable can be optimized out, we should
use count (from descriptor) in place of upperBound. Descriptor being paramter
gives better reliability at higher optimization levels.
Below program now shows better debugging with -O2
Inside fun, array1 can be seen.
```
subroutine fun (array1, array2)
integer :: array1 (:, :)
real    :: array2 (:, :, :)
array1(:,:) = 5
array1(1, 1) = 30
array2(:,:,:) = 6
array2(:,:,:) = 3
array2(1,1,1) = 30
array2(3,3,3) = 90
end subroutine
program vla_sub
interface
subroutine fun (array1, array2)
integer :: array1 (:, :)
real :: array2 (:, :, :)
end subroutine
end interface …
```
> [DebugInfo] Debug support for assumed shape array at higher optimizations

- test/f90_correct/inc/dtio01.mk
- test/f90_correct/lit/dtio01.sh
- test/f90_correct/src/dtio01.f90
- tools/flang1/flang1exe/semantio.c
The standard specifies: “If there is no v-list in the edit descriptor or if the data transfer statement speciﬁes list-directed or namelist formatting, the processor shall provide v_list as a zero-sized array.” flang fails to do this.
This patch meets the requirement by making a zero-sized array and providing it to `v_list`
> Fix the bug where the `v_list` argument is not provided as a zero-sized array in some cases as required by the standard.

- test/debug_info/use_only_test.f90
- test/debug_info/use_only_test.f90_mod.f90
- test/debug_info/usemodule.f90
- tools/flang2/flang2exe/cgmain.cpp
- tools/flang2/flang2exe/ll_write.cpp
- tools/flang2/flang2exe/lldebug.cpp
- tools/flang2/flang2exe/lldebug.h
Consider the testcase below
```
module mymod
integer :: var1 = 11
integer :: var2 = 12
integer :: var3 = 13
end module mymod
Program main
call use_renamed()
contains
subroutine use_renamed()
use mymod, var4 => var1
print *, var4
end subroutine use_renamed
end program main
```
Which currently produces IR as
```
!0 = !DIGlobalVariableExpression(var: !1, expr: !DIExpression())
!1 = distinct !DIGlobalVariable(name: "var1", scope: !2, file: !3, line: 2, type: !9, isLocal: false, isDefinition: true)
!2 = !DIModule(scope: !4, name: "mymod", file: !3, line: 1)
!3 = !DIFile(filename: "usemodulealias.f90", directory: "/tmp")
!4 = distinct !DICompileUnit(language: DW_LANG_Fortran90, file: !3, producer: " F90 Flang - 1.5 2017-05-01", isOptimized: false, flags: "'+flang -g -S -emit-llvm …
```
> [DebugInfo] Use enhanced DIImportedEntity to generate better IR for renamed modules

- test/llvm_ir_correct/fp_reduce.f90
- test/llvm_ir_correct/fp_reduce_intrinsic.f90
- tools/flang2/docs/xflag.n
- tools/flang2/flang2exe/cgmain.cpp
- tools/flang2/flang2exe/llutil.h
This patch adds the nsz, reassoc attributes to arithmetic instructions.
These attributes helps with vectorisation of loops containing
reductions.
Also included are testcases.
This commit requires corresponding change to be submitted on the classic-flang-llvm-project repository in order to have all of the test cases passing!
> Add attributes to IR instructions

- test/llvm_ir_correct/fp_reduce_intrinsic.f90
In order to make this test pass, this patch modifies it towards being more generic and less specific.
> tests: the fp_reduce_intrinsic.f90 test case was using non-existing features

- runtime/libpgmath/lib/common/fpcvt.c
libpgmath should be able to use `errno` directly, without having to go through `libflangrti`. Decoupling the libraries not only allows libpgmath to be used independently, but also fixes compiler warnings about undeclared functions.
> [LLVM 15][libpgmath] Decouple from libflangrti by using errno directly; NFCI

- runtime/flang/comm.c
- runtime/flang/desc.c
- runtime/flang/descRW.c
- runtime/flang/descRW.h
- runtime/flang/fioMacros.h
- runtime/flang/gather.c
- runtime/flang/gathscat.c
- runtime/flang/mmul.c
- runtime/flang/olap.c
- runtime/flang/red.h
- runtime/flang/reduct.c
- runtime/flang/scatter.c
- runtime/flang/scatter.h
Classic Flang code uses tables of functions (with different argument types) to achieve polymorphism. Previously, such a function was declared as `void (*p)()`, to allow any function to be assigned to the function pointer variable `p`. But when a call to such a function pointer is attempted, Clang 15 now emits warnings like these:
```
.../flang/runtime/flang/comm.c:97:14: error: passing arguments to a function without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
sk->start(sk->arg, rb, sb, rd, sd);
^
.../flang/runtime/flang/comm.c:117:13: error: passing arguments to a function without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
sk->free(sk->arg);
^
```
To …
> [LLVM 15][runtime] Define overloaded function types and improve type checking

- test/lit.site.cfg.in
The previous change to `lit.site.cfg.in` would generate an explicit `if` statement in the output file, e.g.
```python
if "x86_64-unknown-linux-gnu":
config.target_triple = "x86_64-unknown-linux-gnu"
else:
config.target_triple = ""
```
...which looks a bit ridiculous.
> [test] Slight aesthetic improvement for previous commit; NFC

- runtime/flang/mmcmplx16.c
- runtime/flang/mmcmplx8.c
- runtime/flang/mmreal4.c
- runtime/flang/mmreal8.c
This fixes errors such as:
```
.../flang/runtime/flang/mmreal8.c:99:21: error: passing arguments to 'ftn_mvmul_real8_' without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
ftn_mvmul_real8_(&ta, &mra, &kab, alpha, a, &lda, b, beta, c);
^
```
> [LLVM 15][runtime] Add C prototypes for external Fortran matmul functions

- runtime/flang/ftni64bitsup.c
- runtime/flang/utilsi64.c
ftni64bitsup.c and utilsi64.c define a static function `shf64` (a helper for shifting signed 64-bit values) identically, while only ftni64bitsup.c defines the unsigned verison `ushf64`. Both files call `shf64` on various unsigned values, causing the compiler to complain. They also declare conflicting prototypes for the same functions, declare some functions as `extern` unnecessarily, and omit forward declarations when they are necessary. This patch fixes all these problems, and makes both files use the same definitions for `shf64` and `ushf64`, reducing code duplication.
> [LLVM 15][runtime] Fix compilation warning in {ftni64bitsup,utilsi64}.c; NFCI

- runtime/flangrti/memalign.c
- tools/flang1/flang1exe/accpp.c
- tools/flang1/flang1exe/fpp.c
- tools/flang1/flang1exe/induc.c
- tools/flang1/flang1exe/parser.c
- tools/flang1/utils/ast/ast.in.h
Delete extern function declarations that already have conflicting prototypes declared earlier/elsewhere. This avoids errors such as:
```
.../flang/tools/flang1/flang1exe/induc.c:517:18: error: a function declaration without a prototype is deprecated in all versions of C and is treated as a zero-parameter prototype in C2x, conflicting with a previous declaration [-Werror,-Wdeprecated-non-prototype]
extern LOGICAL bv_mem();
^
.../flang/tools/flang1/flang1exe/optimize.h:749:9: note: conflicting prototype is here
LOGICAL bv_mem(int *, int);
```
In some cases, the function declaration is modified to complete the prototype.
> [LLVM 15][runtime] Avoid -Wdeprecated-non-prototype warnings; NFC

- tools/flang1/flang1exe/comm.c
- tools/flang1/flang1exe/commopt.c
- tools/flang1/flang1exe/extern.h
- tools/flang1/flang1exe/gbldefs.h
- tools/flang1/flang1exe/semant.c
- tools/flang1/flang1exe/semant.h
- tools/flang1/flang1exe/vsub.c
tools/flang1/flang1exe/vsub.c and tools/flang1/flang1exe/extern.h have different prototypes for the function `vsub`. This patch makes them consistent to avoid the following compiler warning:
```
error: argument 'order2' of type 'int[]' with mismatched bound [-Werror,-Warray-parameter]
```
> [LLVM 15][flang1] Clean up duplicate declarations of MAXDIMS; fix is_ordered prototype

- runtime/flang/mmreal16.c
This is a completion of a previous commit that added C prototypes for external Fortran matmul functions by adding them to the functions in mmreal16.c
> [runtime] Add C prototypes for external Fortran matmul functions (mmreal16.c)

- test/f90_correct/inc/allocatable_function_10.mk
- test/f90_correct/inc/remove_deep_deallocatable.mk
- test/f90_correct/lit/allocatable_function_10.sh
- test/f90_correct/lit/remove_deep_deallocatable.sh
- test/f90_correct/src/allocatable_function_10.f08
- test/f90_correct/src/remove_deep_deallocatable.f08
- tools/flang1/flang1exe/func.c
Flang skips deep allocation for a compiler-generated temporary variable,
but does not check this condition for its deallocation counterpart.
This fix adds a condition check to address this problem.
> [flang1] Skip deep deallocation for allocatable temporary variable

- CMakeLists.txt
- runtime/include/float128.h
- runtime/libpgmath/lib/common/float128.h
128 bit float is not supported on Windows platform and it causes build error.
> win: use long double instead of __float128 on Windows platform

- test/f90_correct/inc/common_02.mk
- test/f90_correct/lit/common_02.sh
- test/f90_correct/src/common_02.f90
- tools/flang1/flang1exe/semant.h
- tools/flang1/flang1exe/semfin.c
- tools/flang1/flang1exe/semutil2.c
- tools/flang2/flang2exe/llassem.cpp
This patch fixes two problems:
1. When two or more `COMMON` blocks with the same name have objects with default initialization, flang will execute each 
initialization more than once. The first pass will carry out normally, whereas the others will be rejected in the `write_comm` 
function, leaving the `DSRT` pointer un-nullified, ultimately causing a segmentation fault.
2. If a common-block-object is of a derived type, the type shall have the BIND attribute or the SEQUENCE attribute and it shall 
have no default initialization. A common-block-object shall not be a derived-type object with an ultimate component that is 
allocatable. flang fails to enforce the above restrictions on derived types.
This patch fixes the 2 problems above by setting `DSRT` to `NULL` at the right time and …
> Add more checkings for derived types in COMMON statements

- .github/workflows/build_flang.yml
- .github/workflows/build_flang_arm64.yml
- CMakeLists.txt
- build-flang.sh
D121838 introduced a new macro for adding lit test suites to an umbrella test suite (e.g. "check-all"). It updated clang/CMakeLists.txt to change how "check-clang" is added to "check-all". This patch applies a similar transformation to Classic Flang's CMakeLists.txt, but retains the original code path so that the code still works for release_14x and older branches. Without this patch, when building Classic Flang with LLVM 15, running "make check-all" would have no effect (it does not invoke "make check-flang").
> [LLVM 15] Make check-all invoke check-flang again

- .github/workflows/build_flang_arm64.yml
Arm's self-hosted AArch64 runner can only be used for actions in the original flang-compiler/flang repo.
> [workflows] Do not try to run AArch64 build job on forks

- include/flang/ArgParser/arg_parser.h
- lib/ArgParser/arg_parser.c
- tools/flang1/flang1exe/main.c
- tools/flang2/flang2exe/main.cpp
Certain elements in `flg.x` are set before `register_xflag_arg` is called. They should not be overwritten when the `-x` command-line option is registered. Instead `flg.x` should be cleared at the beginning of the `main` function.
> [ArgParser] Do not zero xflags when registering command line option

- .github/workflows/build_flang.yml
- .github/workflows/build_flang_arm64.yml
As discussed at the 2022/11/02 call, going forward the `master` branch will only
support opaque pointer IR, while the `legacy` branch will continue to support
legacy IR with older classic-flang-llvm-project release branches.
> [workflows] Build and test master branch with release_15x only

- .github/workflows/build_flang.yml
- .github/workflows/build_flang_arm64.yml
- build-flang.sh
This patch adds the `-b` option to `build-flang.sh` which lets the user specify an alternate location for the build directories of libpgmath and flang (both will be placed under the same build prefix), and the `-x` option which lets the user specify additional CMake options when configuring flang.
> [workflows] Add build script options to allow customization

- runtime/libpgmath/CMakeLists.txt
Basically QUADFP is disabled in Flang on Windows on ARM, so this setting should be applied in libpgmath as well until we make sure about it supported corretly.
> win: Disable QUADFP build in libpgmath for Windows on ARM

- test/debug_info/allocatable_arr_param.f90
- test/debug_info/assumed_rank.f90
- test/debug_info/assumed_shape.f90
- test/debug_info/assumed_shape_non_contiguous.f90
- test/debug_info/assumed_size_array.f90
- test/debug_info/byval-name.f90
- test/debug_info/cray_ptr_param.f90
- test/debug_info/pointer_arr_param.f90
- test/debug_info/pointer_array_openmp.f90
- test/debug_info/prolog.f90
- test/debug_info/redundant_inst.f90
- test/debug_info/result_var.f90
- test/debug_info/retained-nodes.f90
- test/debug_info/scalar_allocatable.f90
- test/directives/getarg.f90
- test/directives/prefetch.f90
- test/llvm_ir_correct/assign_cray_pointer_in_data.f
- test/llvm_ir_correct/daz.f90
- test/llvm_ir_correct/len_intrinsic.f90
- test/llvm_ir_correct/omp_atomic_load_logical.f90
- test/llvm_ir_correct/save.f90
- tools/flang2/flang2exe/cgmain.cpp
- tools/flang2/flang2exe/ll_structure.cpp
- tools/flang2/flang2exe/ll_write.cpp
- tools/flang2/flang2exe/ll_write.h
- tools/flang2/flang2exe/llassem.cpp
- tools/flang2/flang2exe/llassem_common.cpp
- tools/flang2/flang2exe/lldebug.cpp
This PR is based on PR #1306 submitted by @pawosm-arm, we have reviewed PR #1306 and made some changes on the original patch. 
For typed pointers generated by functions, we modify the function in ll_structrue.cpp to uniformly use 'ptr' as the IR output string.
For some hard-coded typed pointers, we rewrite them with 'ptr', and remove some redundant cast_ops between pointers.
We also modify some test cases that use typed pointer IR.
In addition, this branch needs to be built with LLVM 15.
> [feature][flang2] Initial support for opaque pointers

- include/flang/ArgParser/arg_parser.h
- lib/ArgParser/arg_parser.c
- tools/flang1/flang1exe/main.c
- tools/flang2/flang2exe/main.cpp
Certain elements in `flg.x` are set before `register_xflag_arg` is called. They should not be overwritten when the `-x` command-line option is registered. Instead `flg.x` should be cleared at the beginning of the main function.
This is the `legacy` branch version of #1317.
> [ArgParser] Do not zero xflags when registering command line option (legacy branch)

- .github/workflows/build_flang.yml
- .github/workflows/build_flang_arm64.yml
`build_flang_arm64.yml` has custom code for cloning the repository, since the workflow runs in a container on a hosted runner. The workflow needs to be given an explicit branch name to check out, otherwise it would always checkout the `master` branch. This patch adds back the missing branch name to fix a push workflow issue on the `legacy` branch, and also shuffles the steps slightly (NFC) to make `build_flang.yml` and `build_flang_arm64.yml` more similar.
> [workflow] Fix push workflow in build_flang_arm64.yml (legacy branch)

- runtime/flang/CMakeLists.txt
- runtime/flangrti/CMakeLists.txt
This patch makes it possible to run flang without setting `LD_LIBRARY_PATH` for the libomp dependency in libflang and libflangrti. This patch adds an `$ORIGIN` rpath to libflang and libflangrti so that it will search for libomp in the same directory as where these libraries are located. Typically, the libraries for a toolchain are installed in the same directory.
This patch fixes #1302.
> [runtime] Specify location of libomp dependency

- runtime/flang/CMakeLists.txt
- runtime/flangrti/CMakeLists.txt
This patch makes it possible to run flang without setting LD_LIBRARY_PATH for the libomp dependency in libflang and libflangrti. This patch adds an $ORIGIN rpath to libflang and libflangrti so that it will search for libomp in the same directory as where these libraries are located. Typically, the libraries for a toolchain are installed in the same directory.
This patch ports #1327 to `legacy`.
> [runtime] Specify location of libomp dependency (legacy)

- test/directives/getarg.f90
- test/directives/prefetch.f90
- test/llvm_ir_correct/save.f90
- tools/flang2/flang2exe/cgmain.cpp
- tools/flang2/flang2exe/ll_ftn.cpp
- tools/flang2/flang2exe/ll_write.cpp
- tools/flang2/flang2exe/llassem_common.cpp
This PR depends on PR #1321, rebase this branch after merging PR #1321 into the master branch.
This PR removes the redundant bitcast instructions generated by functions as well as the redundant bitcast instructions in some hard-coded strings, and for some hard-coded typed pointers in code blocks controlled by conditional compilation macros, we rewrite them. We also modify some test cases that use redundant bitcast instructions.
> [flang2] Full support for opaque pointers

- runtime/flang/close.c
- runtime/flang/ent3f.h
- runtime/flang/entry.c
- runtime/flang/stat.c
- runtime/flangrti/trace.c
It needs to include the proper header files to silence warnings for
access, chdir, chmod, ulink, write functions.
> Fix implicit declaration of function warnings reported by clang-cl

- scripts/build_flang.py
The 'append' method should be used instead of extend, since the 'extend' method treats the arguments as an iterable object, so extends the current list with list of characters.
> win: Fix the build with verbose options

- runtime/flang/ftncharsup.c
Ftn_strcmp_klen return value type should be int like
its similar sibling functions and like the compiler
assumes when generating a call to this function.
Signed-off-by: Itay Bookstein <itay.bookstein@nextsilicon.com>
> libflang: Fix strcmp_klen return value type

- runtime/include/float128.h
- runtime/libpgmath/lib/common/float128.h
Clang doesn't support `__float128` on Windows and Darwin, so for now we fall back to defining `float128_t` as `long double`. Also keep the macro usage consistent between the two versions of `float128.h`, and stop using `LINUX8664` which is duplicated by `TARGET_LINUX_X8664`, as far as I can tell.
Fixes #1343. This is just a workaround; if quad-precision FP support is desired on X86 Windows and Darwin, someone will need to figure out how to get proper support from Clang and the system libraries on those platforms.
> [runtime] Only use __float128 on Linux

- runtime/flang/getvolinfo3f.c
error: passing arguments to 'GetVolumeInformationA' without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
Also removed the superfluous x86 case.
Added proper Windows types for 'GetVolumeInformationA' function.
> win: Fixed missing prototype error reported by Clang 15

- include/fp-folding.h
- lib/scutil/host-fp-folding.c
- lib/scutil/legacy-folding-api.c
On Windows 'complex' or '_Compex' keyword doesn't supported by clang-cl.
Microsoft uses structure types for representing Complex number.
Since complex numbers aren't native type, the standard arithmetic
operators aren't defined on complex types.
Implicit conversions aren't defined between complex types.
> [win][scutil] Add support Windows Complex types for pow folding

- test/f90_correct/inc/acl04.mk
- test/f90_correct/lit/acl04.sh
- test/f90_correct/src/acl04.f90
- tools/flang1/flang1exe/semutil2.c
When the array constructor element is array of dynamic char, the length can only be checked in runtime, in which case we cannot use `eq_dtype` to check if the two dtypes are equal since the length could be two different asts containing the length info.
This bug should exist long time ago, and it was hidden by 0918a2f2d. It was exposed again in a545a61c9.
> [flang1] Fix a regression about array constructor

- runtime/flang/iso_c_bind.F95
- test/f90_correct/inc/qc45.mk
- test/f90_correct/lit/qc45.sh
- test/f90_correct/src/qc45.f08
When `TARGET_SUPPORTS_QUADFP` is set, `C_LONG_DOUBLE_COMPLEX` in ISO C binding should refer to quad-precision complex numbers; otherwise, it refers to double-precision complex numbers (which is the current behaviour).
> [QuadFP][runtime] Define C_LONG_DOUBLE_COMPLEX as correct type kind

- CMakeLists.txt
- build-flang.sh
- runtime/libpgmath/cmake/modules/HandleOutOfTreeLLVM.cmake
- test/lit.cfg
A backward-compatible solution to a problem caused by the changes introduced in the LLVM 16.0.
I've found inability to refer to the LLVM sources particularly painful for classic-flang, and I guess this will many times be a source of heavy confusion for our end-users even with my patch. I tend to agree with an alternative solution which is to revert the patch that drops `--src-root` flag from `llvm-config` in our clone of the LLVM project.
> cmake: stop asking llvm-config for src-root as it is not supported since LLVM16.0

- test/f90_correct/inc/en06.mk
- test/f90_correct/inc/en07.mk
- test/f90_correct/inc/en08.mk
- test/f90_correct/inc/en09.mk
- test/f90_correct/lit/en06.sh
- test/f90_correct/lit/en07.sh
- test/f90_correct/lit/en08.sh
- test/f90_correct/lit/en09.sh
- test/f90_correct/src/en06.f90
- test/f90_correct/src/en07.f90
- test/f90_correct/src/en08.f90
- test/f90_correct/src/en09.f90
- tools/flang2/flang2exe/cgmain.cpp
- tools/flang2/flang2exe/x86_64/ll_abi.cpp
Fixing the issue 1336.
currently the address of entry return value is stored when the entry return type is pointer. this gives incorrect result.
The fix addresses the issue by storing the scalar return value to the entry return value.
> Fix issue 1336. incorrect results with entry statements

- test/f90_correct/inc/norm2_expr_arg.mk
- test/f90_correct/lit/norm2_expr_arg.sh
- test/f90_correct/src/norm2_expr_arg.F90
- tools/flang1/flang1exe/func.c
When the arguments of NORM2 are expressions they are not getting lowered and hence results in compiler internal error. This change lowers the expression arguments and handles such cases.
A testcase is also added to validate the change.
> Fix for issue # 1361. Flang does not allow expression as argument for NORM2

- scripts/build_flang.py
Native Ninja is available for Windows on ARM,
so it can be used for both Windows platform.
> script: Use Ninja on Windows on ARM

- test/llvm_ir_correct/collapse_zero_assignment.f90
- test/llvm_ir_correct/collapse_zero_assignment_quadfp.f90
- tools/flang1/flang1exe/transfrm.c
If an array is assigned a quad-precision complex value, and the value has a zero real part and a zero imaginary part, the array assignment can be collapsed into a `memset`.
> [QuadFP][flang1] Support quad complex zero in collapse_assignment

- test/f90_correct/inc/import_mod_from_user.mk
- test/f90_correct/lit/import_mod_from_user.sh
- test/f90_correct/makefile
- test/f90_correct/src/import_mod_from_user.f90
- test/f90_correct/src/import_mod_from_user_dir1_m2.f90
- test/f90_correct/src/import_mod_from_user_dir2_m1.f90
- test/f90_correct/src/import_mod_from_user_dir2_m2.f90
- tools/flang1/flang1exe/interf.c
This bug came from 0bcbadbf3f7f056b298a7724b9689ebacbdae4e9, which uses strdup to allocate non-const versions of const string, but does not change the use of the original string. The use of original string (file name) terminates the string by removing the last directory. So, we need to replace the use of original string with the allocated string.
> [Flang1] Fix the string operation of file name

- .github/workflows/build_flang.yml
- .github/workflows/build_flang_arm64.yml
- test/CMakeLists.txt
- test/ncar_kernels/PORT_binterp/src/kernel_binterp.F90
- test/ncar_kernels/PORT_reftra_sw/src/kernel_reftra_sw.F90
This PR fixes a couple of failures in the NCAR tests on X86, adds a new Makefile goal named `check-flang-long`, and updates the GitHub CI workflow to run that instead of `check-all`.  `check-all` remains synonymous to `check-flang`, which skips the NCAR kernel tests as `UNSUPPORTED`.
> Enable NCAR kernel tests

- runtime/flang/ftnmiscsup.c
Give sprintf one extra byte to write the null character in the end of string and resolve the overflow warning
> Fix sprintf overflow

- test/ili_correct/lit.local.cfg
> fix missing local lit config file in ili_correct test folder

- test/llvm_ir_correct/include-self.f90
- tools/flang1/flang1exe/accpp.c
- tools/flang1/flang1exe/fpp.c
A silly bug that prevented building OpenMPI OOT.
> Fix for handling absolute include paths

- test/lit.cfg
On Windows concatenating strings for variables`%flang1` and `%flang2`  are incorrect (config.flang + '1' or '2') e.g.: `path\to\flang.exe1` instead of `path\to\flang1.exe`. 
related issue: #1363
> Fix executable names in lit.cfg

- runtime/flang/bcopys.c
- test/f90_correct/inc/issue1406.mk
- test/f90_correct/lit/issue1406.sh
- test/f90_correct/src/issue1406.f90
Fix a downward-counting loop with an unsigned loop counter to exit when the counter reaches 0 (instead of -1, which never happens).
Closes #1406.
> [runtime] Fix infinite loop in `__fort_bcopysl`

- test/debug_info/use_only_test.f90
- test/debug_info/usemodule.f90
- tools/flang2/flang2exe/ll_structure.h
- tools/flang2/flang2exe/lldebug.cpp
Symptom: Compilation of any Fortran program with imports (USE statement) fails with assert in compiler backend.
Diagnosis: LLVM-17 expects imports list in retainedNode field of DISubprogram wihch while Flang is still generating it as imports field of DICompilationUnit.
Fix: Flang is now updated to new IR as expected by LLVM-17.
> Fix failures for imports with LLVM-17

- test/debug_info/entry_argument_1.f90
- tools/flang2/flang2exe/cgmain.cpp
- tools/flang2/flang2exe/cgmain.h
- tools/flang2/flang2exe/lldebug.cpp
When the compiler generates debuginfo, it does not consider that when there is an entry, the number of arguments will increase by one.
We can fix this problem by getting the returned information by process_ll_abi_func_ftn_mod function, and using the new number of arguments.
> Fix an entry statement debuginfo bug

- test/mp_correct/inc/do20.mk
- test/mp_correct/lit/do20.sh
- test/mp_correct/src/do20.f90
- tools/flang1/flang1exe/lowerilm.c
When the stride of parallel do is negative, flang will always exit loop.
It is because check_loop_bound function always check the incr of a loop
to avoid out of loop bound. It is not necessary since __kmp_for_static_init
in openmp have do the same thing, and will change the stride to match
the actual number of iterations. The function is only needed when SCHEDULE
is enabled.
> [flang1] Fix a parallel do bug

- test/f90_correct/inc/cont01.mk
- test/f90_correct/lit/cont01.sh
- test/f90_correct/src/c_cont01.c
- test/f90_correct/src/cont01.f90
- tools/flang1/flang1exe/rest.c
When array dummy arguments are marked with **contiguous** attribute, the compiler need to generate and pass sequential copy of formal arguments.
This issue is fixed as part of this commit.
> [flang1] Fix the issue with contiguous dummy argument arrays (#1426)

- test/directives/align_array_variable.f90
- test/directives/align_character_variable.f90
- test/directives/align_derived_variable.f90
- test/directives/align_not_supported.f90
- test/flang2/Inputs/nop.ilm
- tools/flang1/flang1exe/dtypeutl.c
- tools/flang1/flang1exe/exterf.c
- tools/flang1/flang1exe/global.h
- tools/flang1/flang1exe/interf.c
- tools/flang1/flang1exe/lower.h
- tools/flang1/flang1exe/lowersym.c
- tools/flang1/flang1exe/semant.c
- tools/flang1/flang1exe/symacc.c
- tools/flang1/flang1exe/symacc.h
- tools/flang1/utils/symtab/symini.cpp
- tools/flang1/utils/symtab/symtab.n
- tools/flang2/docs/xflag.n
- tools/flang2/flang2exe/dtypeutl.cpp
- tools/flang2/flang2exe/llassem.cpp
- tools/flang2/flang2exe/symacc.cpp
- tools/flang2/flang2exe/symacc.h
- tools/flang2/flang2exe/upper.cpp
- tools/flang2/flang2exe/upper.h
- tools/flang2/utils/symtab/symini.cpp
- tools/flang2/utils/symtab/symtab.n
- tools/shared/pragma.c
- tools/shared/utils/global.h
- tools/shared/utils/symacc.c
- tools/shared/utils/symacc.h
- tools/shared/utils/symutil.cpp
Add support for aligning the first address of some type with configurable alignment.
The overall idea for this patch set is as follows:
- add flg.x[251] for saving pragma alignment value in `do_sw()`
- add the stg_align field in `STG_MEMBERS(dt)` to save the pragma alignment value corresponding to the dtype
- update the alignment value in `alignment()` and `lower_put_datatype()` in flang1
- parse the pragma alignment value passed by flang1 through stb in flang2 in `read_datatype()`
- update the alignment value in `alignment()` in flang2
- each common block should be aligned to the largest alignment value of the type it contains, flang2 should update the expected alignment of a block in `gen_acon_expr()`
- the offset of each object to relative common block should be aligned to relative …
> [RFC]Add align pragma for derived type and fix shape array/character type

- .github/workflows/build_flang.yml
- .github/workflows/build_flang_arm64.yml
- .github/workflows/build_flang_windows.yml
Use the Ubuntu 22.04 runner and the `release_16x` and `release_17x` branches of classic-flang-llvm-project to build and test Classic Flang. We use the pre-built classic-flang-llvm-project for building, so we do not actually need to install a specific version of GCC. Also simplify the logic for finding and downloading a suitable prebuilt compiler.
> [workflows] Update GitHub workflows

- test/directives/align_function_var.f90
- test/directives/align_local_var_init.f90
- test/directives/align_local_var_no_init.f90
- test/directives/align_module_var_init.f90
- test/directives/align_module_var_no_init.f90
- test/directives/align_subroutine_var.f90
Add support for aligning the first address of scalar data types (integer, logical, real, complex) with align pragma like "!dir$ align n".
For example: 
```fortran
!dir$ align 128
integer(kind=4) :: a
```
The align pragma enables the first address of variable "a" to be an integer multiple of 128.
The overall idea for this patch is as follows:
* flang1:
1. recognize the align pragma in the source code in `do_sw()`
2. add a field to the `ST_VAR` symbol table to store the align value
3. add `ALIGN_PRAGMA *align_pragma_base` to store all the align pragmas info parsed in the first pass
4. match all the align pragmas and corresponding variables and  set the variable's align value at the end of parse
5. print the variable's align value in `lower_symbol()`
* flang2:
1. add a field to the `ST_VAR` …
> Add align pragma for scalar data types (integer, logical, real, complex)

- test/llvm_ir_correct/attr.f90
- test/llvm_ir_correct/vscale-mbits.f90
- test/llvm_ir_correct/vscale.f90
This is a preparation patch for ensuring LLVM18 compatibility.
> NFC: The checks for AArch64 target features must be more flexible after Oliver Stannard's LLVM commit

- test/directives/nounroll.f90
- test/directives/nounroll2.f90
- test/directives/unroll.f90
- test/directives/unroll_override.f90
- test/directives/vector_vectorlength_integer.f90
- test/directives/vector_vectorlength_num_fixed.f90
- test/directives/vector_vectorlength_num_scalable.f90
- test/directives/vector_vectorlength_scalable.f90
This is a preparation patch for ensuring LLVM18 compatibility.
> NFC: With LLVM18 a loop preheader is being exposed, hence the preds must be more liberal

- test/f90_correct/inc/bound17.mk
- test/f90_correct/lit/bound17.sh
- test/f90_correct/src/bound17.f90
- tools/flang1/flang1exe/func.c
This regression referred in issue #1442 occurs when we pass a struct component for an assumed-shape formal argument, e.g. `geom%freq` in
```fortran
alpha = alpha_dyn_qho(alpha_0, omega, geom%freq, dalpha, grad_request_t())
```
where the third formal argument is declared as
```fortran
type(quad_pt_t), intent(in) :: freq(0:)
```
The root cause is that we have lost the parent `geom` in the expression for the descriptor of `geom%freq` when using the function `get_extent`.
We fix this by manually constructing the subscript expression for the extent of `geom%freq`.
> Fix regression introduced by PR #1422

- .github/workflows/build_flang.yml
- .github/workflows/build_flang_arm64.yml
- .github/workflows/build_flang_windows.yml
`release_16x` test jobs are now failing because the prebuilt `classic-flang-llvm-project` binaries on GitHub have expired.
Also, we have renamed the Ubuntu container image generated by the `classic-flang-llvm-project` workflow; it needs to be renamed in the workflow for this repository as well.
> [workflows] Update CI to test release_18x, and stop testing release_16x

- .github/workflows/build_flang.yml
This fixes a workflow failure caused by the deprecation of older versions of the action:
https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
> [workflows] Update CI to use actions/upload-artifact@v4

- test/lex/backslash.f90
flang should use the last specified option when both these options are used. e.g Mbaskslash should be used when "-Mnobackslash -Mbackslash <filename>" arguments are specified.
> [NFC] modifying the testcase by adding Mbackslash and Mnobackslash options together

- CMakeLists.txt
- runtime/flang/gather.c
- runtime/flang/gathscat.c
- runtime/flang/red_count.c
- runtime/flang/scatter.c
- runtime/flang/scatter.h
- runtime/flangrti/CMakeLists.txt
- runtime/flangrti/trace_lin.c
- test/lit.cfg
- tools/flang1/flang1exe/semutil2.c
- tools/flang1/flang1exe/state.h
When building Classic Flang with Clang 19, the compiler produces numerous `-Wcast-function-type-mismatch` warnings. Also, `libflangrti.so` fails to link and tests fail to run, since the OpenMP library `libomp.so` is now installed in a different location by default. This PR fixes these issues, in a way that should be compatible with the `release_18x` branch.
> Fix build failures when using Clang 19

- test/debug_info/allocatable_arr_param.f90
- test/debug_info/assumed_rank.f90
- test/debug_info/assumed_shape.f90
- test/debug_info/assumed_shape_non_contiguous.f90
- test/debug_info/assumed_size_array.f90
- test/debug_info/byval-name.f90
- test/debug_info/conststring.f90
- test/debug_info/cray_ptr_param.f90
- test/debug_info/enum.f90
- test/debug_info/parameter.f90
- test/debug_info/pointer_arr_param.f90
- test/debug_info/pointer_array_openmp.f90
- test/debug_info/prolog.f90
- test/debug_info/result_var.f90
- test/debug_info/retained-nodes.f90
- test/debug_info/scalar_allocatable.f90
- test/lit.cfg
Upstream LLVM has eliminated debug intrinsics like `@llvm.dbg.value()` and `@llvm.dbg.declare()`, and replaced them with `DPValue` objects that are printed as `#dbg_value()` and `#dbg_declare()`. This patch modifies the FileCheck patterns in the tests to match, and make them require the `llvm-19` feature.
> [DebugInfo][test] Fix tests for LLVM 19 compatibility

- test/llvm_ir_correct/Inputs/tbaa_multimod_01_input.f90
- test/llvm_ir_correct/Inputs/tbaa_multimod_02_input.f90
- test/llvm_ir_correct/tbaa_multimod_01.f90
- test/llvm_ir_correct/tbaa_multimod_02.f90
- tools/flang2/flang2exe/cgmain.cpp
Currently, functions within the same module are assigned unique TBAA type system IDs based on their order, but functions in different modules can unintentionally receive the same ID, leading to incorrect non-aliasing results. This patch resolves the issue by appending a hash of the module name to each function type system metadata, ensuring unique type systems across modules and preventing aliasing errors. This resolves #1458.
> [Flang2] Fix duplicate TBAA type systems across modules
