flang-compiler/flang

tools/flang1/flang1exe/sharedefs.h, tools/flang1/utils/symtab/symacc.c, tools/flang2/flang2exe/kmpcutil.c, tools/flang2/flang2exe/listing.c, tools/flang2/flang2exe/sharedefs.h, tools/flang2/flang2exe/symacc.c, tools/flang2/flang2exe/xref.c, tools/flang2/utils/symtab/symacc.c
Results of running automated scan:
$ ./review-helper
Check commit message...
Git status...
nothing to commit, working directory clean
Bad .orig or .rej files...
=> Remove PG-names from Flang

tools/flang1/flang1exe/semfunc.c, tools/flang1/flang1exe/sharedefs.h, tools/flang1/utils/symtab/symacc.c, tools/flang2/flang2exe/kmpcutil.c, tools/flang2/flang2exe/listing.c, tools/flang2/flang2exe/sharedefs.h, tools/flang2/flang2exe/symacc.c, tools/flang2/flang2exe/xref.c, tools/flang2/utils/symtab/symacc.c
Manually reviewed changes.
Result of automated scan:
Check commit message...
Git status...
nothing to commit, working directory clean
Bad .orig or .rej files...
Bad strings...
=> Fix problem with intrinsic c_sizeof()

tools/flang1/flang1exe/ast.c, tools/flang1/flang1exe/lower.h, tools/flang1/flang1exe/lowerilm.c, tools/flang1/flang1exe/mp.h, tools/flang1/flang1exe/semant.c, tools/flang1/flang1exe/semant.h, tools/flang1/flang1exe/semant3.c, tools/flang1/flang1exe/semsmp.c, tools/flang1/flang1exe/semutil.c, tools/flang1/utils/prstab/gram.txt, tools/flang2/flang2exe/kmpcutil.c, tools/flang2/flang2exe/mp.h, tools/flang2/flang2exe/outliner.c, tools/flang2/flang2exe/upper.h
Manually reviewed change.
Results of automated review:
Check commit message...
Git status...
nothing to commit, working directory clean
Bad .orig or .rej files...
Bad strings...
=> Fix missing extern declaration

tools/flang1/flang1exe/dump.c, tools/flang1/flang1exe/findloop.c, tools/flang1/flang1exe/lowerilm.c, tools/flang1/flang1exe/miscutil.c, tools/flang1/flang1exe/optimize.c, tools/flang1/flang1exe/optimize.h, tools/flang1/flang1exe/pointsto.c, tools/flang2/flang2exe/llassem.c, tools/flang2/flang2exe/miscutil.c, tools/flang2/utils/ilmtp/x86_64/ilmtp.n
We have three commits from NVIDIA that we would like to pull in to flang-compiler/master.
More application of STG_ macros for data management  …			f012252
Fix ILM macro for LEQV8 - missing IKMV OP			
Clean up macros, ifdefs in llassem.c  …			f6a5457
This is the first of several pull requests we should see today.
=> Pull 2017-05-26T09:35

tools/flang1/flang1exe/miscutil.c, tools/flang1/flang1exe/sharedefs.h, tools/flang2/flang2exe/bih.h, tools/flang2/flang2exe/ili.h, tools/flang2/flang2exe/miscutil.c, tools/flang2/flang2exe/sharedefs.h, tools/flang2/utils/ilitp/ilitp.cpp
=> Pull-2017-05-26T15-00

tools/flang1/flang1exe/bblock.c, tools/flang1/flang1exe/semant.h, tools/flang1/flang1exe/semant3.c, tools/flang1/flang1exe/semfunc.c, tools/flang1/flang1exe/semutil2.c, tools/flang2/flang2exe/verify.c
=> Pull-2017-05-26T16-34

tools/flang2/flang2exe/ll_write.c
Code cleanup; simplification of printf->fputs/fputc
=> Pull-2017-05-30T15-10

lib/scutil/legacy-folding-api.c, runtime/CMakeLists.txt, test/f90_correct/backslash.f90, tools/flang1/flang1exe/expand.h, tools/flang1/flang1exe/lz.c, tools/flang1/flang1exe/main.c, tools/flang1/flang1exe/semfin.c, tools/flang1/flang1exe/semfunc.c, tools/flang2/flang2exe/dinit.c, tools/flang2/flang2exe/expand.h, tools/flang2/flang2exe/ll_structure.c, tools/flang2/flang2exe/ll_write.c, tools/flang2/flang2exe/llassem.c, tools/flang2/flang2exe/llassem.h, tools/flang2/flang2exe/lldebug.c, tools/flang2/flang2exe/lldebug.h, tools/flang2/flang2exe/llutil.c, tools/flang2/flang2exe/ppc64le-Linux/ll_abi.c
Bring in recent changes from NVIDIA.
=> Pull-2017-06-02T09-12

runtime/flangrti/mcopy1.c, runtime/flangrti/mcopy2.c, runtime/flangrti/mcopy4.c, runtime/flangrti/mcopy8.c, runtime/flangrti/mset1.c, runtime/flangrti/mset2.c, runtime/flangrti/mset4.c, runtime/flangrti/mset8.c, runtime/flangrti/mzero1.c, runtime/flangrti/mzero2.c, runtime/flangrti/mzero4.c, runtime/flangrti/mzero8.c, tools/flang2/flang2exe/ll_ftn.c, tools/flang2/flang2exe/llassem.c, tools/flang2/flang2exe/main.c
=> Pull-2017-06-05T10-07

include/flang/Error/errmsg-accel.n, tools/flang1/flang1exe/rest.c, tools/flang2/flang2exe/cgmain.c, tools/flang2/flang2exe/expand.c, tools/flang2/flang2exe/iltutil.c
=> Pull 2017-06-16T15-30 Recent NVIDIA Changes

README.md
Now as LLNL/spack#5503 and LLNL/spack#5459 is merged, here is bit of documentation on how to use it.
/cc @hfinkel @tgamblin @AlexisPerry
=> README.md: add section about spack

tools/flang2/flang2exe/cgmain.c
VBLEND mask might be a hoisted invariant value
If so, reloading the temporary vector mask will be a DTYPE, while
LLVM SELECT instruction needs an i1 bitmask. Thus we need to
convert the vector mask to a bitmask. The integer case was already
there but not the floating point cases.
=> Pull 2018-02-06T07-36 Recent NVIDIA Changes

tools/flang2/flang2exe/cgraph.h, tools/flang2/flang2exe/exputil.c, tools/flang2/flang2exe/exputil.h, tools/flang2/flang2exe/fastset.c, tools/flang2/flang2exe/llassem.h, tools/flang2/flang2exe/llassem_common.c, tools/flang2/flang2exe/llassem_common.h, tools/flang2/flang2exe/llopt.c, tools/flang2/flang2exe/llsched.c, tools/flang2/flang2exe/llutil.h, tools/flang2/flang2exe/machreg.c, tools/flang2/flang2exe/mwd.c, tools/flang2/flang2exe/semant.h, tools/flang2/flang2exe/semsym.c, tools/flang2/flang2exe/semsym.h, tools/flang2/flang2exe/symfun.h, tools/flang2/flang2exe/upper.c, tools/shared/pragma.c, tools/shared/salloc.c
Code cleanup - convert more files to a C++ friendly form.
=> Pull 2018-06-14T17-27 Recent NVIDIA Changes

test/tools/check_compilation.py, tools/flang1/flang1exe/semant3.c
Add check_compilation.py to flang
Also update a comment in semant3.c.
=> Pull 2018-06-29T11-41 Recent NVIDIA Changes

runtime/libpgmath/lib/common/arm64intrin.h
Add missing runtime/libpgmath/lib/common/arm64intrin.h
=> Pull 2018-07-25T13-56 Recent NVIDIA Changes

tools/flang2/flang2exe/llassem.c
=> Use zeroinitializer instead of hard to handle stream of zeros

lib/ADT/hash.c, lib/ArgParser/arg_parser.c, lib/ArgParser/debug_action.c, tools/flang2/flang2exe/exp_rte.c, tools/flang2/flang2exe/llassem.c, tools/flang2/flang2exe/main.c, tools/flang2/flang2exe/scope.h
flang2 updates for C++ compilation
Also add some debug code to llassem.c
=> Pull 2018-08-17T09-46 Recent NVIDIA Changes

include/flang/Error/errmsg-in.n, tools/flang1/flang1exe/outconv.c, tools/flang1/flang1exe/semant.c, tools/flang1/flang1exe/semant3.c, tools/flang1/flang1exe/semfunc.c, tools/flang1/flang1exe/semutil.c, tools/flang1/flang1exe/semutil2.c, tools/flang2/docs/xflag.n, tools/flang2/flang2exe/cgmain.cpp, tools/flang2/flang2exe/exp_ftn.cpp, tools/flang2/flang2exe/iliutil.cpp, tools/flang2/flang2exe/ll_write.cpp, tools/flang2/flang2exe/ll_write.h
Files that look like "no change" have metadata changes (file permissions).
=> Pull 2018-12-12T13-57 Recent NVIDIA Changes

runtime/flangrti/trace.c, tools/flang1/flang1exe/semant3.c, tools/flang2/docs/xflag.n, tools/flang2/flang2exe/cgmain.cpp, tools/flang2/flang2exe/cgmain.h, tools/flang2/flang2exe/exp_rte.cpp, tools/flang2/flang2exe/ll_structure.h, tools/flang2/flang2exe/ll_write.cpp, tools/flang2/flang2exe/lldebug.cpp, tools/flang2/flang2exe/symtab.cpp, tools/flang2/utils/ilitp/x86_64/ilitp.n
Simpler pull request of recent changes than #708.
=> Pull 2019-04-30T16-05 Recent NVIDIA Changes

tools/flang2/flang2exe/llassem.cpp
Fix issue with OpenMP offload build
=> Pull 2019-07-30T14-22 Recent NVIDIA Changes

runtime/flang/CMakeLists.txt, runtime/flang/norm2.F95, runtime/flang/norm2.h, runtime/flang/red_norm2.c, runtime/flang/red_norm2_stride1.c
Integrate the norm2 routines into flang runtime
1. Setup cmake instructions for preprocessing
and building norm2
2. Improve the preprocessing of fortran files,
by using ${CMAKE_Fortran_COMPILER} instead of
${CMAKE_C_COMPILER}
=> Pull 2019-08-24T10-24 Recent NVIDIA Changes

runtime/libpgmath/lib/x86_64/libm_amd.h, runtime/libpgmath/lib/x86_64/powi/powi_128.c, runtime/libpgmath/lib/x86_64/powi/powi_256.c, test/f90_correct/inc/oop734.mk, tools/flang1/flang1exe/dinit.c, tools/flang2/flang2exe/expsmp.cpp, tools/flang2/flang2exe/iliutil.cpp, tools/flang2/flang2exe/kmpcutil.cpp, tools/flang2/flang2exe/main.cpp, tools/flang2/flang2exe/ompaccel.cpp, tools/flang2/flang2exe/ompaccel.h, tools/flang2/flang2exe/outliner.cpp, tools/flang2/flang2exe/outliner.h, tools/flang2/flang2exe/tgtutil.cpp, tools/flang2/flang2exe/tgtutil.h, tools/shared/mp.h
A couple of small commits and a large set of changes for OpenMP target offload support.
This should also fix issues with FLANG_OPENMP_GPU_NVIDIA=OFF builds.
=> Pull 2019-09-18T12-50 Recent NVIDIA Changes

include/flang/Error/errmsg-in.n, runtime/flang/type.c, tools/flang1/flang1exe/dpm_out.c, tools/flang1/flang1exe/lowerilm.c, tools/flang1/flang1exe/lowersym.c, tools/flang1/flang1exe/semant3.c, tools/flang1/flang1exe/semstk.h, tools/flang1/flang1exe/semutil.c, tools/flang1/flang1exe/semutil2.c, tools/flang1/flang1exe/transfrm.c, tools/shared/rtlRtns.c, tools/shared/rtlRtns.h
This also fixes Flang issues #244 and #721.
=> Add F2008 polymorphic allocatable assignment

lib/ArgParser/arg_parser.c, tools/flang1/flang1exe/accpp.c, tools/flang1/flang1exe/assem.c, tools/flang1/flang1exe/ast.c, tools/flang1/flang1exe/astout.c, tools/flang1/flang1exe/comm.c, tools/flang1/flang1exe/comm.h, tools/flang1/flang1exe/comminvar.c, tools/flang1/flang1exe/commopt.c, tools/flang1/flang1exe/commopt.h, tools/flang1/flang1exe/datadep.c, tools/flang1/flang1exe/detect.c, tools/flang1/flang1exe/dinit.c, tools/flang1/flang1exe/scan.c
Some spelling fixes for flang1exe
=> Spelling Fixes

test/flang2/Inputs/nop.ilm, test/flang2/invocation.ilm, test/flang2/lit.local.cfg, test/lit.cfg, tools/flang2/flang2exe/main.cpp
Add null checks to solve several obvious crash bugs.
=> [flang2] Fix segmentation faults (#421)

test/llvm_ir_correct/reshape_allocatable_order.f90
PR #966 has fixed the problems which can be reproduced by the minimal reproducer introduced in this commit.
=> tests: one test case supporting PR #966

test/llvm_ir_correct/named_arguments.f90, tools/flang1/flang1exe/module.c
This commit contains a test case supporting the need for this change.
The fix itself was worked out by Michal Paszta.
=> Fix for regression introduced by PR #922 (issue #995)

test/f90_correct/subcallx.f90
Additional test case for commit e74bd56b48fe7278024227fed0a38ef5f8d39214
=> Test case for capturing procedure pointers to OpenMP parallel regions

test/debug_info/redundant-lexicalblock.f90
Thanks! @pawosm-arm for the heads up :)
=> [DebugInfo] Test case update for #895

tools/flang2/flang2exe/CMakeLists.txt, tools/flang2/flang2exe/aarch64-Linux/flgdf.h, tools/flang2/flang2exe/cgmain.cpp, tools/flang2/flang2exe/expand.cpp, tools/flang2/flang2exe/exputil.cpp, tools/flang2/flang2exe/iliutil.cpp, tools/flang2/flang2exe/kmpcutil.cpp, tools/flang2/flang2exe/ll_structure.cpp, tools/flang2/flang2exe/ll_structure.h, tools/flang2/flang2exe/ll_write.cpp, tools/flang2/flang2exe/llassem.cpp, tools/flang2/flang2exe/lldebug.cpp, tools/flang2/flang2exe/main.cpp, tools/flang2/flang2exe/outliner.cpp, tools/flang2/flang2exe/ppc64le-Linux/flgdf.h, tools/flang2/flang2exe/symacc.cpp, tools/flang2/flang2exe/upper.cpp, tools/flang2/flang2exe/x86_64-Linux/flgdf.h, tools/shared/utils/global.h
Also add linker directives option.
=> patch flang2 to work on windows

test/directives/dir_forceinline.f90, test/directives/dir_noinline.f90, tools/flang2/docs/xflag.n, tools/flang2/flang2exe/cgmain.cpp, tools/shared/pragma.c
Apologies for the new PR, due to my misunderstanding, I deleted the repository forks from which the original PRs were created (closed the older PRs).
@kiranchandramohan This PR fixes the issue of attribute not coming up with `-g` option as well.
=> [Flang2] Support for noinline/forceinline pragmas

tools/flang2/flang2exe/outliner.cpp
Commit fdd777cee941eb7df368a54abad2de4dff744194 added some code that creates a NME for an address in the uplevel table (conceptually a struct with many anonymous fields) if one does not exist, in order to make the dumps easier to read (presumably there would otherwise be many stores associated with the same NME, which would be confusing). However, instead of looking for a struct member with a matching offset, the function `member_with_offset` clobbers the `ADDRESS` field for the first `SPTR` in the given linked list of members. This patch corrects the function, and also fixes some formatting problems in the code that calls `member_with_offset`.
=> [flang2] Fix member_with_offset in outliner.cpp

runtime/libpgmath/lib/common/fltmanip.c, runtime/libpgmath/lib/common/iqnint.c, runtime/libpgmath/lib/common/kqnint.c
These format issues were introduced by commit https://github.com/flang-compiler/flang/commit/31d2ca5bc01f92d99299cd352af1eb9eb90eecae . 
@pawosm-arm left comments as follow:
https://github.com/flang-compiler/flang/pull/1129#discussion_r701761429
https://github.com/flang-compiler/flang/pull/1129#discussion_r701763812
=> [libpgmath] Fix several format issues; NFCI

test/llvm_ir_correct/assign_cray_pointer_in_data.f, tools/flang2/flang2exe/llassem_common.cpp
=> Add missing signed integer to a pointer conversion in DATA statement

runtime/flang/init.c, tools/flang2/flang2exe/iliutil.cpp
This PR aims to fix the build issue for Windows.
=> win: Fix type mismatch char* vs const char*

.github/workflows/build_flang.yml
update artifact repo url to fork
clean up
add release13 branch
remove cpp option from matrix
remove matrix.include in workflow
install gcc11, g++11
=> Introduction of gcc-11 to CI

test/debug_info/module.f90, tools/flang2/flang2exe/ll_write.cpp, tools/flang2/flang2exe/lldebug.cpp
This PR is same as https://github.com/flang-compiler/flang/pull/898/ to support modules debug info. i recreated this fresh PR for the same fix. please note 898 has the approval of @bryanpkc already.
=> [DebugInfo] Corrected debuginfo for modules

test/llvm_ir_correct/invalid_ambiguous_generic_proc.f90, test/llvm_ir_correct/invalid_public_entity_error.f90
adding the reproducer testcases to support the pull request #966
=> two additional testcases to support the pull request #966

test/f90_correct/inc/ptr_to_internal_proc.mk, test/f90_correct/lit/ptr_to_internal_proc.sh, test/f90_correct/src/ptr_to_internal_proc.f90, tools/flang1/flang1exe/semant.c
This change is based on the solution discussed in #872.
The test case code comes from the bug report.
=> A test confirming that the issue #872 is actually resolved.

build-flang.sh
Useful when using these scripts for development
Signed-off-by: Richard Barton <richard.barton@arm.com>
=> Enhance build scripts to enable a debug build

test/f90_correct/inc/transpose_init.mk, test/f90_correct/lit/transpose_init.sh, test/f90_correct/src/transpose_init.f90, tools/flang1/flang1exe/semant.h, tools/flang1/flang1exe/semutil2.c, tools/flang2/flang2exe/dinit.cpp, tools/flang2/flang2exe/semant.h
Transpose intrinsic is a special case of the reshape intrinsic
with the order parameter set to /2,1/. We reuse the functions
for reshape intrinsic with minor additions wherever possible.
=> Changes to support transpose intrinsic during initialization

test/llvm_ir_correct/fma.f90, tools/flang2/docs/xflag.n, tools/flang2/flang2exe/cgmain.cpp, tools/flang2/flang2exe/cgmain.h
This is a companion to the PR on the LLVM side: https://github.com/flang-compiler/classic-flang-llvm-project/pull/113
=> Add fp-contract=fast flag and attach to LLVM IR.

.gitignore, scripts/build_flang.py, scripts/cmake/toolchain_linux_x86_64.cmake, scripts/cmake/toolchain_windows_amd64.cmake, scripts/cmake/toolchain_windows_arm64.cmake, scripts/settings.py
This commit aims to replace shell script with a python scripts to build
Flang easier on Windows as well.
* Also add 'pyc' to .gitignore.
=> Add a platform independent build script for Flang

test/llvm_ir_correct/vscale-mbits.f90, tools/flang2/flang2exe/cgmain.cpp
Same commit https://github.com/flang-compiler/flang/pull/1319 pushed to `legacy` branch
=> [flang2] Pass -vscale_range_max=0 to mean an unbounded range (legacy)

tools/flang2/flang2exe/CMakeLists.txt
=> [flang2] Install into the same bin directory as flang1

runtime/flang/comm.c
Adjust the functions signatures to match the expected function pointer signatures
=> Adjust the functions signatures to match the expected function pointer signatures

test/lit.cfg
* Enable running Flang tests on Windows
=> Add Windows support to lit.cfg

runtime/flang/eoshift.c, runtime/flang/fill.c, runtime/flang/map.c, runtime/flang/mget.c, runtime/flang/mmul.c, runtime/flang/olap.c, runtime/flang/pack.c, runtime/flang/red.c, runtime/flang/reshape.c, runtime/flang/scal.c, runtime/flang/scalar_copy.c, runtime/flang/type.c, runtime/flangrti/tempnam.c, runtime/flangrti/trace.c, test/debug_info/debug_module_import.f90, test/debug_info/redundant_inst.f90, test/lit.cfg, tools/flang1/flang1exe/dtypeutl.c, tools/flang1/flang1exe/dtypeutl.h, tools/flang1/flang1exe/hash.c, tools/flang1/flang1exe/semfunc.c, tools/flang1/utils/ast/astutil.c
- Fix new compile-time warnings (`-Wcast-qual`).
- Fix test cases for LLVM 17 compatibility.
=> Upgrade to LLVM 17

test/llvm_ir_correct/dllimport_test.f90, test/llvm_ir_correct/dllimport_test.f90_mod.f90, tools/flang2/flang2exe/llassem.cpp
=> Fix the dllimport code generation for opaque type

.github/workflows/build_flang_windows.yml
This fixes the CI failures that are currently blocking multiple PRs. After this PR is merged, those affected PRs will need to be rebased.
=> [workflow] Fix syntax bugs in Windows CI action
